// Generated by CIRCT firtool-1.56.1
module Branch(
  input  [3:0]  io_br_type,
  input  [31:0] io_src1,
                io_src2,
                io_pc_ex,
                io_imm_ex,
  input         io_predict_jump,
  input  [31:0] io_pred_npc,
  output        io_real_jump,
                io_predict_fail,
  output [31:0] io_branch_target
);

  wire [31:0] _io_branch_target_output;
  wire        _GEN = io_br_type == 4'h4;
  wire        _io_real_jump_T = io_src1 == io_src2;
  wire        _GEN_0 = io_br_type == 4'h5;
  wire        _io_real_jump_T_1 = io_src1 != io_src2;
  wire        _GEN_1 = io_br_type == 4'h6;
  wire        _GEN_2 = io_br_type == 4'h7;
  wire        _GEN_3 = io_br_type == 4'h8;
  wire        _io_real_jump_T_8 = io_src1 < io_src2;
  wire        _GEN_4 = io_br_type == 4'h9;
  wire        _io_real_jump_T_9 = io_src1 >= io_src2;
  wire        _GEN_5 = io_br_type == 4'h1;
  wire        _GEN_6 = io_br_type == 4'h2;
  wire        _GEN_7 = io_br_type == 4'h3;
  assign _io_branch_target_output =
    _GEN | _GEN_0 | _GEN_1 | _GEN_2 | _GEN_3 | _GEN_4 | ~_GEN_5
      ? io_pc_ex + io_imm_ex
      : io_src1 + io_imm_ex;
  assign io_real_jump =
    _GEN
      ? _io_real_jump_T
      : _GEN_0
          ? _io_real_jump_T_1
          : _GEN_1
              ? $signed(io_src1) < $signed(io_src2)
              : _GEN_2
                  ? $signed(io_src1) >= $signed(io_src2)
                  : _GEN_3
                      ? _io_real_jump_T_8
                      : _GEN_4 ? _io_real_jump_T_9 : _GEN_5 | _GEN_6 | _GEN_7;
  assign io_predict_fail =
    _GEN
      ? _io_real_jump_T ^ io_predict_jump | io_predict_jump
        & io_pred_npc != _io_branch_target_output
      : _GEN_0
          ? _io_real_jump_T_1 ^ io_predict_jump | io_predict_jump
            & io_pred_npc != _io_branch_target_output
          : _GEN_1
              ? $signed(io_src1) < $signed(io_src2) ^ io_predict_jump | io_predict_jump
                & io_pred_npc != _io_branch_target_output
              : _GEN_2
                  ? $signed(io_src1) >= $signed(io_src2) ^ io_predict_jump
                    | io_predict_jump & io_pred_npc != _io_branch_target_output
                  : _GEN_3
                      ? _io_real_jump_T_8 ^ io_predict_jump | io_predict_jump
                        & io_pred_npc != _io_branch_target_output
                      : _GEN_4
                          ? _io_real_jump_T_9 ^ io_predict_jump | io_predict_jump
                            & io_pred_npc != _io_branch_target_output
                          : _GEN_5
                              ? ~io_predict_jump | io_predict_jump
                                & io_pred_npc != _io_branch_target_output
                              : _GEN_6
                                  ? ~io_predict_jump | io_predict_jump
                                    & io_pred_npc != _io_branch_target_output
                                  : _GEN_7
                                    & (~io_predict_jump | io_predict_jump
                                       & io_pred_npc != _io_branch_target_output);
  assign io_branch_target = _io_branch_target_output;
endmodule

