// Generated by CIRCT firtool-1.58.0
module Bypass(
  input  [6:0]  io_prd_wb,
                io_prj_ex,
                io_prk_ex,
  input  [31:0] io_prf_wdata_wb,
  input         io_rd_valid_wb,
  output        io_forward_prj_en,
                io_forward_prk_en,
  output [31:0] io_forward_prj_data,
                io_forward_prk_data
);

  assign io_forward_prj_en = io_rd_valid_wb & io_prd_wb == io_prj_ex;
  assign io_forward_prk_en = io_rd_valid_wb & io_prd_wb == io_prk_ex;
  assign io_forward_prj_data = io_prf_wdata_wb;
  assign io_forward_prk_data = io_prf_wdata_wb;
endmodule

