// Generated by CIRCT firtool-1.58.0
module Bypass_2(
  input  [6:0]  io_prd_wb_0,
                io_prd_wb_1,
                io_prj_ex_0,
                io_prj_ex_1,
                io_prk_ex_0,
                io_prk_ex_1,
  input  [31:0] io_prf_wdata_wb_0,
                io_prf_wdata_wb_1,
  input         io_rd_valid_wb_0,
                io_rd_valid_wb_1,
  output        io_forward_prj_en_0,
                io_forward_prj_en_1,
                io_forward_prk_en_0,
                io_forward_prk_en_1,
  output [31:0] io_forward_prj_data_0,
                io_forward_prj_data_1,
                io_forward_prk_data_0,
                io_forward_prk_data_1
);

  wire _io_forward_prj_data_0_T = io_prd_wb_0 == io_prj_ex_0;
  wire _io_forward_prk_data_0_T = io_prd_wb_0 == io_prk_ex_0;
  wire _io_forward_prj_data_1_T = io_prd_wb_0 == io_prj_ex_1;
  wire _io_forward_prk_data_1_T = io_prd_wb_0 == io_prk_ex_1;
  assign io_forward_prj_en_0 =
    io_rd_valid_wb_0 & _io_forward_prj_data_0_T | io_rd_valid_wb_1
    & io_prd_wb_1 == io_prj_ex_0;
  assign io_forward_prj_en_1 =
    io_rd_valid_wb_0 & _io_forward_prj_data_1_T | io_rd_valid_wb_1
    & io_prd_wb_1 == io_prj_ex_1;
  assign io_forward_prk_en_0 =
    io_rd_valid_wb_0 & _io_forward_prk_data_0_T | io_rd_valid_wb_1
    & io_prd_wb_1 == io_prk_ex_0;
  assign io_forward_prk_en_1 =
    io_rd_valid_wb_0 & _io_forward_prk_data_1_T | io_rd_valid_wb_1
    & io_prd_wb_1 == io_prk_ex_1;
  assign io_forward_prj_data_0 =
    io_rd_valid_wb_0 & _io_forward_prj_data_0_T ? io_prf_wdata_wb_0 : io_prf_wdata_wb_1;
  assign io_forward_prj_data_1 =
    io_rd_valid_wb_0 & _io_forward_prj_data_1_T ? io_prf_wdata_wb_0 : io_prf_wdata_wb_1;
  assign io_forward_prk_data_0 =
    io_rd_valid_wb_0 & _io_forward_prk_data_0_T ? io_prf_wdata_wb_0 : io_prf_wdata_wb_1;
  assign io_forward_prk_data_1 =
    io_rd_valid_wb_0 & _io_forward_prk_data_1_T ? io_prf_wdata_wb_0 : io_prf_wdata_wb_1;
endmodule

