// Generated by CIRCT firtool-1.58.0
module FU1_EX_WB_Reg(
  input         clock,
                reset,
                io_flush,
                io_inst_pack_EX_rd_valid,
  input  [6:0]  io_inst_pack_EX_prd,
  input  [5:0]  io_inst_pack_EX_rob_index,
  input         io_inst_pack_EX_inst_valid,
  input  [31:0] io_alu_out_EX,
  output        io_inst_pack_WB_rd_valid,
  output [6:0]  io_inst_pack_WB_prd,
  output [5:0]  io_inst_pack_WB_rob_index,
  output        io_inst_pack_WB_inst_valid,
  output [31:0] io_alu_out_WB
);

  reg        inst_pack_reg_rd_valid;
  reg [6:0]  inst_pack_reg_prd;
  reg [5:0]  inst_pack_reg_rob_index;
  reg        inst_pack_reg_inst_valid;
  reg [31:0] alu_out_reg;
  always @(posedge clock) begin
    if (reset) begin
      inst_pack_reg_rd_valid <= 1'h0;
      inst_pack_reg_prd <= 7'h0;
      inst_pack_reg_rob_index <= 6'h0;
      inst_pack_reg_inst_valid <= 1'h0;
      alu_out_reg <= 32'h0;
    end
    else begin
      inst_pack_reg_rd_valid <= ~io_flush & io_inst_pack_EX_rd_valid;
      inst_pack_reg_prd <= io_flush ? 7'h0 : io_inst_pack_EX_prd;
      inst_pack_reg_rob_index <= io_flush ? 6'h0 : io_inst_pack_EX_rob_index;
      inst_pack_reg_inst_valid <= ~io_flush & io_inst_pack_EX_inst_valid;
      alu_out_reg <= io_flush ? 32'h0 : io_alu_out_EX;
    end
  end // always @(posedge)
  assign io_inst_pack_WB_rd_valid = inst_pack_reg_rd_valid;
  assign io_inst_pack_WB_prd = inst_pack_reg_prd;
  assign io_inst_pack_WB_rob_index = inst_pack_reg_rob_index;
  assign io_inst_pack_WB_inst_valid = inst_pack_reg_inst_valid;
  assign io_alu_out_WB = alu_out_reg;
endmodule

