// Generated by CIRCT firtool-1.58.0
module Imm_Gen(
  input  [31:0] io_inst,
  input  [3:0]  io_imm_type,
  output [31:0] io_imm
);

  assign io_imm =
    io_imm_type == 4'h0
      ? 32'h0
      : io_imm_type == 4'h1
          ? {27'h0, io_inst[14:10]}
          : io_imm_type == 4'h2
              ? {20'h0, io_inst[21:10]}
              : io_imm_type == 4'h3
                  ? {{20{io_inst[21]}}, io_inst[21:10]}
                  : io_imm_type == 4'h4
                      ? {{14{io_inst[25]}}, io_inst[25:10], 2'h0}
                      : io_imm_type == 4'h5
                          ? {io_inst[24:5], 12'h0}
                          : io_imm_type == 4'h6
                              ? {{4{io_inst[9]}}, io_inst[9:0], io_inst[25:10], 2'h0}
                              : 32'h0;
endmodule

