// Generated by CIRCT firtool-1.58.0
module RN_DP_Reg(
  input         clock,
                reset,
                io_flush,
                io_stall,
  input  [31:0] io_insts_pack_RN_0_pc,
  input         io_insts_pack_RN_0_inst_valid,
                io_insts_pack_RN_0_predict_jump,
  input  [31:0] io_insts_pack_RN_0_pred_npc,
  input         io_insts_pack_RN_0_rj_valid,
                io_insts_pack_RN_0_rk_valid,
                io_insts_pack_RN_0_rd_valid,
  input  [31:0] io_insts_pack_RN_0_imm,
  input  [4:0]  io_insts_pack_RN_0_alu_op,
  input  [1:0]  io_insts_pack_RN_0_alu_rs1_sel,
                io_insts_pack_RN_0_alu_rs2_sel,
  input  [3:0]  io_insts_pack_RN_0_br_type,
  input  [4:0]  io_insts_pack_RN_0_mem_type,
  input  [1:0]  io_insts_pack_RN_0_fu_id,
  input  [6:0]  io_insts_pack_RN_0_prj,
                io_insts_pack_RN_0_prk,
                io_insts_pack_RN_0_prd,
  input  [5:0]  io_insts_pack_RN_0_rob_index,
  input  [31:0] io_insts_pack_RN_1_pc,
  input         io_insts_pack_RN_1_inst_valid,
                io_insts_pack_RN_1_predict_jump,
  input  [31:0] io_insts_pack_RN_1_pred_npc,
  input         io_insts_pack_RN_1_rj_valid,
                io_insts_pack_RN_1_rk_valid,
                io_insts_pack_RN_1_rd_valid,
  input  [31:0] io_insts_pack_RN_1_imm,
  input  [4:0]  io_insts_pack_RN_1_alu_op,
  input  [1:0]  io_insts_pack_RN_1_alu_rs1_sel,
                io_insts_pack_RN_1_alu_rs2_sel,
  input  [3:0]  io_insts_pack_RN_1_br_type,
  input  [4:0]  io_insts_pack_RN_1_mem_type,
  input  [1:0]  io_insts_pack_RN_1_fu_id,
  input  [6:0]  io_insts_pack_RN_1_prj,
                io_insts_pack_RN_1_prk,
                io_insts_pack_RN_1_prd,
  input  [5:0]  io_insts_pack_RN_1_rob_index,
  input         io_insts_pack_RN_1_prj_raw,
                io_insts_pack_RN_1_prk_raw,
  input  [31:0] io_insts_pack_RN_2_pc,
  input         io_insts_pack_RN_2_inst_valid,
                io_insts_pack_RN_2_predict_jump,
  input  [31:0] io_insts_pack_RN_2_pred_npc,
  input         io_insts_pack_RN_2_rj_valid,
                io_insts_pack_RN_2_rk_valid,
                io_insts_pack_RN_2_rd_valid,
  input  [31:0] io_insts_pack_RN_2_imm,
  input  [4:0]  io_insts_pack_RN_2_alu_op,
  input  [1:0]  io_insts_pack_RN_2_alu_rs1_sel,
                io_insts_pack_RN_2_alu_rs2_sel,
  input  [3:0]  io_insts_pack_RN_2_br_type,
  input  [4:0]  io_insts_pack_RN_2_mem_type,
  input  [1:0]  io_insts_pack_RN_2_fu_id,
  input  [6:0]  io_insts_pack_RN_2_prj,
                io_insts_pack_RN_2_prk,
                io_insts_pack_RN_2_prd,
  input  [5:0]  io_insts_pack_RN_2_rob_index,
  input         io_insts_pack_RN_2_prj_raw,
                io_insts_pack_RN_2_prk_raw,
  input  [31:0] io_insts_pack_RN_3_pc,
  input         io_insts_pack_RN_3_inst_valid,
                io_insts_pack_RN_3_predict_jump,
  input  [31:0] io_insts_pack_RN_3_pred_npc,
  input         io_insts_pack_RN_3_rj_valid,
                io_insts_pack_RN_3_rk_valid,
                io_insts_pack_RN_3_rd_valid,
  input  [31:0] io_insts_pack_RN_3_imm,
  input  [4:0]  io_insts_pack_RN_3_alu_op,
  input  [1:0]  io_insts_pack_RN_3_alu_rs1_sel,
                io_insts_pack_RN_3_alu_rs2_sel,
  input  [3:0]  io_insts_pack_RN_3_br_type,
  input  [4:0]  io_insts_pack_RN_3_mem_type,
  input  [1:0]  io_insts_pack_RN_3_fu_id,
  input  [6:0]  io_insts_pack_RN_3_prj,
                io_insts_pack_RN_3_prk,
                io_insts_pack_RN_3_prd,
  input  [5:0]  io_insts_pack_RN_3_rob_index,
  input         io_insts_pack_RN_3_prj_raw,
                io_insts_pack_RN_3_prk_raw,
  output [31:0] io_insts_pack_DP_0_pc,
  output        io_insts_pack_DP_0_inst_valid,
                io_insts_pack_DP_0_predict_jump,
  output [31:0] io_insts_pack_DP_0_pred_npc,
  output        io_insts_pack_DP_0_rj_valid,
                io_insts_pack_DP_0_rk_valid,
                io_insts_pack_DP_0_rd_valid,
  output [31:0] io_insts_pack_DP_0_imm,
  output [4:0]  io_insts_pack_DP_0_alu_op,
  output [1:0]  io_insts_pack_DP_0_alu_rs1_sel,
                io_insts_pack_DP_0_alu_rs2_sel,
  output [3:0]  io_insts_pack_DP_0_br_type,
  output [4:0]  io_insts_pack_DP_0_mem_type,
  output [1:0]  io_insts_pack_DP_0_fu_id,
  output [6:0]  io_insts_pack_DP_0_prj,
                io_insts_pack_DP_0_prk,
                io_insts_pack_DP_0_prd,
  output [5:0]  io_insts_pack_DP_0_rob_index,
  output [31:0] io_insts_pack_DP_1_pc,
  output        io_insts_pack_DP_1_inst_valid,
                io_insts_pack_DP_1_predict_jump,
  output [31:0] io_insts_pack_DP_1_pred_npc,
  output        io_insts_pack_DP_1_rj_valid,
                io_insts_pack_DP_1_rk_valid,
                io_insts_pack_DP_1_rd_valid,
  output [31:0] io_insts_pack_DP_1_imm,
  output [4:0]  io_insts_pack_DP_1_alu_op,
  output [1:0]  io_insts_pack_DP_1_alu_rs1_sel,
                io_insts_pack_DP_1_alu_rs2_sel,
  output [3:0]  io_insts_pack_DP_1_br_type,
  output [4:0]  io_insts_pack_DP_1_mem_type,
  output [1:0]  io_insts_pack_DP_1_fu_id,
  output [6:0]  io_insts_pack_DP_1_prj,
                io_insts_pack_DP_1_prk,
                io_insts_pack_DP_1_prd,
  output [5:0]  io_insts_pack_DP_1_rob_index,
  output        io_insts_pack_DP_1_prj_raw,
                io_insts_pack_DP_1_prk_raw,
  output [31:0] io_insts_pack_DP_2_pc,
  output        io_insts_pack_DP_2_inst_valid,
                io_insts_pack_DP_2_predict_jump,
  output [31:0] io_insts_pack_DP_2_pred_npc,
  output        io_insts_pack_DP_2_rj_valid,
                io_insts_pack_DP_2_rk_valid,
                io_insts_pack_DP_2_rd_valid,
  output [31:0] io_insts_pack_DP_2_imm,
  output [4:0]  io_insts_pack_DP_2_alu_op,
  output [1:0]  io_insts_pack_DP_2_alu_rs1_sel,
                io_insts_pack_DP_2_alu_rs2_sel,
  output [3:0]  io_insts_pack_DP_2_br_type,
  output [4:0]  io_insts_pack_DP_2_mem_type,
  output [1:0]  io_insts_pack_DP_2_fu_id,
  output [6:0]  io_insts_pack_DP_2_prj,
                io_insts_pack_DP_2_prk,
                io_insts_pack_DP_2_prd,
  output [5:0]  io_insts_pack_DP_2_rob_index,
  output        io_insts_pack_DP_2_prj_raw,
                io_insts_pack_DP_2_prk_raw,
  output [31:0] io_insts_pack_DP_3_pc,
  output        io_insts_pack_DP_3_inst_valid,
                io_insts_pack_DP_3_predict_jump,
  output [31:0] io_insts_pack_DP_3_pred_npc,
  output        io_insts_pack_DP_3_rj_valid,
                io_insts_pack_DP_3_rk_valid,
                io_insts_pack_DP_3_rd_valid,
  output [31:0] io_insts_pack_DP_3_imm,
  output [4:0]  io_insts_pack_DP_3_alu_op,
  output [1:0]  io_insts_pack_DP_3_alu_rs1_sel,
                io_insts_pack_DP_3_alu_rs2_sel,
  output [3:0]  io_insts_pack_DP_3_br_type,
  output [4:0]  io_insts_pack_DP_3_mem_type,
  output [1:0]  io_insts_pack_DP_3_fu_id,
  output [6:0]  io_insts_pack_DP_3_prj,
                io_insts_pack_DP_3_prk,
                io_insts_pack_DP_3_prd,
  output [5:0]  io_insts_pack_DP_3_rob_index,
  output        io_insts_pack_DP_3_prj_raw,
                io_insts_pack_DP_3_prk_raw
);

  reg [31:0] insts_pack_reg_0_pc;
  reg        insts_pack_reg_0_inst_valid;
  reg        insts_pack_reg_0_predict_jump;
  reg [31:0] insts_pack_reg_0_pred_npc;
  reg        insts_pack_reg_0_rj_valid;
  reg        insts_pack_reg_0_rk_valid;
  reg        insts_pack_reg_0_rd_valid;
  reg [31:0] insts_pack_reg_0_imm;
  reg [4:0]  insts_pack_reg_0_alu_op;
  reg [1:0]  insts_pack_reg_0_alu_rs1_sel;
  reg [1:0]  insts_pack_reg_0_alu_rs2_sel;
  reg [3:0]  insts_pack_reg_0_br_type;
  reg [4:0]  insts_pack_reg_0_mem_type;
  reg [1:0]  insts_pack_reg_0_fu_id;
  reg [6:0]  insts_pack_reg_0_prj;
  reg [6:0]  insts_pack_reg_0_prk;
  reg [6:0]  insts_pack_reg_0_prd;
  reg [5:0]  insts_pack_reg_0_rob_index;
  reg [31:0] insts_pack_reg_1_pc;
  reg        insts_pack_reg_1_inst_valid;
  reg        insts_pack_reg_1_predict_jump;
  reg [31:0] insts_pack_reg_1_pred_npc;
  reg        insts_pack_reg_1_rj_valid;
  reg        insts_pack_reg_1_rk_valid;
  reg        insts_pack_reg_1_rd_valid;
  reg [31:0] insts_pack_reg_1_imm;
  reg [4:0]  insts_pack_reg_1_alu_op;
  reg [1:0]  insts_pack_reg_1_alu_rs1_sel;
  reg [1:0]  insts_pack_reg_1_alu_rs2_sel;
  reg [3:0]  insts_pack_reg_1_br_type;
  reg [4:0]  insts_pack_reg_1_mem_type;
  reg [1:0]  insts_pack_reg_1_fu_id;
  reg [6:0]  insts_pack_reg_1_prj;
  reg [6:0]  insts_pack_reg_1_prk;
  reg [6:0]  insts_pack_reg_1_prd;
  reg [5:0]  insts_pack_reg_1_rob_index;
  reg        insts_pack_reg_1_prj_raw;
  reg        insts_pack_reg_1_prk_raw;
  reg [31:0] insts_pack_reg_2_pc;
  reg        insts_pack_reg_2_inst_valid;
  reg        insts_pack_reg_2_predict_jump;
  reg [31:0] insts_pack_reg_2_pred_npc;
  reg        insts_pack_reg_2_rj_valid;
  reg        insts_pack_reg_2_rk_valid;
  reg        insts_pack_reg_2_rd_valid;
  reg [31:0] insts_pack_reg_2_imm;
  reg [4:0]  insts_pack_reg_2_alu_op;
  reg [1:0]  insts_pack_reg_2_alu_rs1_sel;
  reg [1:0]  insts_pack_reg_2_alu_rs2_sel;
  reg [3:0]  insts_pack_reg_2_br_type;
  reg [4:0]  insts_pack_reg_2_mem_type;
  reg [1:0]  insts_pack_reg_2_fu_id;
  reg [6:0]  insts_pack_reg_2_prj;
  reg [6:0]  insts_pack_reg_2_prk;
  reg [6:0]  insts_pack_reg_2_prd;
  reg [5:0]  insts_pack_reg_2_rob_index;
  reg        insts_pack_reg_2_prj_raw;
  reg        insts_pack_reg_2_prk_raw;
  reg [31:0] insts_pack_reg_3_pc;
  reg        insts_pack_reg_3_inst_valid;
  reg        insts_pack_reg_3_predict_jump;
  reg [31:0] insts_pack_reg_3_pred_npc;
  reg        insts_pack_reg_3_rj_valid;
  reg        insts_pack_reg_3_rk_valid;
  reg        insts_pack_reg_3_rd_valid;
  reg [31:0] insts_pack_reg_3_imm;
  reg [4:0]  insts_pack_reg_3_alu_op;
  reg [1:0]  insts_pack_reg_3_alu_rs1_sel;
  reg [1:0]  insts_pack_reg_3_alu_rs2_sel;
  reg [3:0]  insts_pack_reg_3_br_type;
  reg [4:0]  insts_pack_reg_3_mem_type;
  reg [1:0]  insts_pack_reg_3_fu_id;
  reg [6:0]  insts_pack_reg_3_prj;
  reg [6:0]  insts_pack_reg_3_prk;
  reg [6:0]  insts_pack_reg_3_prd;
  reg [5:0]  insts_pack_reg_3_rob_index;
  reg        insts_pack_reg_3_prj_raw;
  reg        insts_pack_reg_3_prk_raw;
  always @(posedge clock) begin
    if (reset) begin
      insts_pack_reg_0_pc <= 32'h0;
      insts_pack_reg_0_inst_valid <= 1'h0;
      insts_pack_reg_0_predict_jump <= 1'h0;
      insts_pack_reg_0_pred_npc <= 32'h0;
      insts_pack_reg_0_rj_valid <= 1'h0;
      insts_pack_reg_0_rk_valid <= 1'h0;
      insts_pack_reg_0_rd_valid <= 1'h0;
      insts_pack_reg_0_imm <= 32'h0;
      insts_pack_reg_0_alu_op <= 5'h0;
      insts_pack_reg_0_alu_rs1_sel <= 2'h0;
      insts_pack_reg_0_alu_rs2_sel <= 2'h0;
      insts_pack_reg_0_br_type <= 4'h0;
      insts_pack_reg_0_mem_type <= 5'h0;
      insts_pack_reg_0_fu_id <= 2'h0;
      insts_pack_reg_0_prj <= 7'h0;
      insts_pack_reg_0_prk <= 7'h0;
      insts_pack_reg_0_prd <= 7'h0;
      insts_pack_reg_0_rob_index <= 6'h0;
      insts_pack_reg_1_pc <= 32'h0;
      insts_pack_reg_1_inst_valid <= 1'h0;
      insts_pack_reg_1_predict_jump <= 1'h0;
      insts_pack_reg_1_pred_npc <= 32'h0;
      insts_pack_reg_1_rj_valid <= 1'h0;
      insts_pack_reg_1_rk_valid <= 1'h0;
      insts_pack_reg_1_rd_valid <= 1'h0;
      insts_pack_reg_1_imm <= 32'h0;
      insts_pack_reg_1_alu_op <= 5'h0;
      insts_pack_reg_1_alu_rs1_sel <= 2'h0;
      insts_pack_reg_1_alu_rs2_sel <= 2'h0;
      insts_pack_reg_1_br_type <= 4'h0;
      insts_pack_reg_1_mem_type <= 5'h0;
      insts_pack_reg_1_fu_id <= 2'h0;
      insts_pack_reg_1_prj <= 7'h0;
      insts_pack_reg_1_prk <= 7'h0;
      insts_pack_reg_1_prd <= 7'h0;
      insts_pack_reg_1_rob_index <= 6'h0;
      insts_pack_reg_1_prj_raw <= 1'h0;
      insts_pack_reg_1_prk_raw <= 1'h0;
      insts_pack_reg_2_pc <= 32'h0;
      insts_pack_reg_2_inst_valid <= 1'h0;
      insts_pack_reg_2_predict_jump <= 1'h0;
      insts_pack_reg_2_pred_npc <= 32'h0;
      insts_pack_reg_2_rj_valid <= 1'h0;
      insts_pack_reg_2_rk_valid <= 1'h0;
      insts_pack_reg_2_rd_valid <= 1'h0;
      insts_pack_reg_2_imm <= 32'h0;
      insts_pack_reg_2_alu_op <= 5'h0;
      insts_pack_reg_2_alu_rs1_sel <= 2'h0;
      insts_pack_reg_2_alu_rs2_sel <= 2'h0;
      insts_pack_reg_2_br_type <= 4'h0;
      insts_pack_reg_2_mem_type <= 5'h0;
      insts_pack_reg_2_fu_id <= 2'h0;
      insts_pack_reg_2_prj <= 7'h0;
      insts_pack_reg_2_prk <= 7'h0;
      insts_pack_reg_2_prd <= 7'h0;
      insts_pack_reg_2_rob_index <= 6'h0;
      insts_pack_reg_2_prj_raw <= 1'h0;
      insts_pack_reg_2_prk_raw <= 1'h0;
      insts_pack_reg_3_pc <= 32'h0;
      insts_pack_reg_3_inst_valid <= 1'h0;
      insts_pack_reg_3_predict_jump <= 1'h0;
      insts_pack_reg_3_pred_npc <= 32'h0;
      insts_pack_reg_3_rj_valid <= 1'h0;
      insts_pack_reg_3_rk_valid <= 1'h0;
      insts_pack_reg_3_rd_valid <= 1'h0;
      insts_pack_reg_3_imm <= 32'h0;
      insts_pack_reg_3_alu_op <= 5'h0;
      insts_pack_reg_3_alu_rs1_sel <= 2'h0;
      insts_pack_reg_3_alu_rs2_sel <= 2'h0;
      insts_pack_reg_3_br_type <= 4'h0;
      insts_pack_reg_3_mem_type <= 5'h0;
      insts_pack_reg_3_fu_id <= 2'h0;
      insts_pack_reg_3_prj <= 7'h0;
      insts_pack_reg_3_prk <= 7'h0;
      insts_pack_reg_3_prd <= 7'h0;
      insts_pack_reg_3_rob_index <= 6'h0;
      insts_pack_reg_3_prj_raw <= 1'h0;
      insts_pack_reg_3_prk_raw <= 1'h0;
    end
    else begin
      if (io_flush) begin
        insts_pack_reg_0_pc <= 32'h0;
        insts_pack_reg_0_pred_npc <= 32'h0;
        insts_pack_reg_0_imm <= 32'h0;
        insts_pack_reg_0_alu_op <= 5'h0;
        insts_pack_reg_0_alu_rs1_sel <= 2'h0;
        insts_pack_reg_0_alu_rs2_sel <= 2'h0;
        insts_pack_reg_0_br_type <= 4'h0;
        insts_pack_reg_0_mem_type <= 5'h0;
        insts_pack_reg_0_fu_id <= 2'h0;
        insts_pack_reg_0_prj <= 7'h0;
        insts_pack_reg_0_prk <= 7'h0;
        insts_pack_reg_0_prd <= 7'h0;
        insts_pack_reg_0_rob_index <= 6'h0;
        insts_pack_reg_1_pc <= 32'h0;
        insts_pack_reg_1_pred_npc <= 32'h0;
        insts_pack_reg_1_imm <= 32'h0;
        insts_pack_reg_1_alu_op <= 5'h0;
        insts_pack_reg_1_alu_rs1_sel <= 2'h0;
        insts_pack_reg_1_alu_rs2_sel <= 2'h0;
        insts_pack_reg_1_br_type <= 4'h0;
        insts_pack_reg_1_mem_type <= 5'h0;
        insts_pack_reg_1_fu_id <= 2'h0;
        insts_pack_reg_1_prj <= 7'h0;
        insts_pack_reg_1_prk <= 7'h0;
        insts_pack_reg_1_prd <= 7'h0;
        insts_pack_reg_1_rob_index <= 6'h0;
        insts_pack_reg_2_pc <= 32'h0;
        insts_pack_reg_2_pred_npc <= 32'h0;
        insts_pack_reg_2_imm <= 32'h0;
        insts_pack_reg_2_alu_op <= 5'h0;
        insts_pack_reg_2_alu_rs1_sel <= 2'h0;
        insts_pack_reg_2_alu_rs2_sel <= 2'h0;
        insts_pack_reg_2_br_type <= 4'h0;
        insts_pack_reg_2_mem_type <= 5'h0;
        insts_pack_reg_2_fu_id <= 2'h0;
        insts_pack_reg_2_prj <= 7'h0;
        insts_pack_reg_2_prk <= 7'h0;
        insts_pack_reg_2_prd <= 7'h0;
        insts_pack_reg_2_rob_index <= 6'h0;
        insts_pack_reg_3_pc <= 32'h0;
        insts_pack_reg_3_pred_npc <= 32'h0;
        insts_pack_reg_3_imm <= 32'h0;
        insts_pack_reg_3_alu_op <= 5'h0;
        insts_pack_reg_3_alu_rs1_sel <= 2'h0;
        insts_pack_reg_3_alu_rs2_sel <= 2'h0;
        insts_pack_reg_3_br_type <= 4'h0;
        insts_pack_reg_3_mem_type <= 5'h0;
        insts_pack_reg_3_fu_id <= 2'h0;
        insts_pack_reg_3_prj <= 7'h0;
        insts_pack_reg_3_prk <= 7'h0;
        insts_pack_reg_3_prd <= 7'h0;
        insts_pack_reg_3_rob_index <= 6'h0;
      end
      else if (io_stall) begin
      end
      else begin
        insts_pack_reg_0_pc <= io_insts_pack_RN_0_pc;
        insts_pack_reg_0_pred_npc <= io_insts_pack_RN_0_pred_npc;
        insts_pack_reg_0_imm <= io_insts_pack_RN_0_imm;
        insts_pack_reg_0_alu_op <= io_insts_pack_RN_0_alu_op;
        insts_pack_reg_0_alu_rs1_sel <= io_insts_pack_RN_0_alu_rs1_sel;
        insts_pack_reg_0_alu_rs2_sel <= io_insts_pack_RN_0_alu_rs2_sel;
        insts_pack_reg_0_br_type <= io_insts_pack_RN_0_br_type;
        insts_pack_reg_0_mem_type <= io_insts_pack_RN_0_mem_type;
        insts_pack_reg_0_fu_id <= io_insts_pack_RN_0_fu_id;
        insts_pack_reg_0_prj <= io_insts_pack_RN_0_prj;
        insts_pack_reg_0_prk <= io_insts_pack_RN_0_prk;
        insts_pack_reg_0_prd <= io_insts_pack_RN_0_prd;
        insts_pack_reg_0_rob_index <= io_insts_pack_RN_0_rob_index;
        insts_pack_reg_1_pc <= io_insts_pack_RN_1_pc;
        insts_pack_reg_1_pred_npc <= io_insts_pack_RN_1_pred_npc;
        insts_pack_reg_1_imm <= io_insts_pack_RN_1_imm;
        insts_pack_reg_1_alu_op <= io_insts_pack_RN_1_alu_op;
        insts_pack_reg_1_alu_rs1_sel <= io_insts_pack_RN_1_alu_rs1_sel;
        insts_pack_reg_1_alu_rs2_sel <= io_insts_pack_RN_1_alu_rs2_sel;
        insts_pack_reg_1_br_type <= io_insts_pack_RN_1_br_type;
        insts_pack_reg_1_mem_type <= io_insts_pack_RN_1_mem_type;
        insts_pack_reg_1_fu_id <= io_insts_pack_RN_1_fu_id;
        insts_pack_reg_1_prj <= io_insts_pack_RN_1_prj;
        insts_pack_reg_1_prk <= io_insts_pack_RN_1_prk;
        insts_pack_reg_1_prd <= io_insts_pack_RN_1_prd;
        insts_pack_reg_1_rob_index <= io_insts_pack_RN_1_rob_index;
        insts_pack_reg_2_pc <= io_insts_pack_RN_2_pc;
        insts_pack_reg_2_pred_npc <= io_insts_pack_RN_2_pred_npc;
        insts_pack_reg_2_imm <= io_insts_pack_RN_2_imm;
        insts_pack_reg_2_alu_op <= io_insts_pack_RN_2_alu_op;
        insts_pack_reg_2_alu_rs1_sel <= io_insts_pack_RN_2_alu_rs1_sel;
        insts_pack_reg_2_alu_rs2_sel <= io_insts_pack_RN_2_alu_rs2_sel;
        insts_pack_reg_2_br_type <= io_insts_pack_RN_2_br_type;
        insts_pack_reg_2_mem_type <= io_insts_pack_RN_2_mem_type;
        insts_pack_reg_2_fu_id <= io_insts_pack_RN_2_fu_id;
        insts_pack_reg_2_prj <= io_insts_pack_RN_2_prj;
        insts_pack_reg_2_prk <= io_insts_pack_RN_2_prk;
        insts_pack_reg_2_prd <= io_insts_pack_RN_2_prd;
        insts_pack_reg_2_rob_index <= io_insts_pack_RN_2_rob_index;
        insts_pack_reg_3_pc <= io_insts_pack_RN_3_pc;
        insts_pack_reg_3_pred_npc <= io_insts_pack_RN_3_pred_npc;
        insts_pack_reg_3_imm <= io_insts_pack_RN_3_imm;
        insts_pack_reg_3_alu_op <= io_insts_pack_RN_3_alu_op;
        insts_pack_reg_3_alu_rs1_sel <= io_insts_pack_RN_3_alu_rs1_sel;
        insts_pack_reg_3_alu_rs2_sel <= io_insts_pack_RN_3_alu_rs2_sel;
        insts_pack_reg_3_br_type <= io_insts_pack_RN_3_br_type;
        insts_pack_reg_3_mem_type <= io_insts_pack_RN_3_mem_type;
        insts_pack_reg_3_fu_id <= io_insts_pack_RN_3_fu_id;
        insts_pack_reg_3_prj <= io_insts_pack_RN_3_prj;
        insts_pack_reg_3_prk <= io_insts_pack_RN_3_prk;
        insts_pack_reg_3_prd <= io_insts_pack_RN_3_prd;
        insts_pack_reg_3_rob_index <= io_insts_pack_RN_3_rob_index;
      end
      insts_pack_reg_0_inst_valid <=
        ~io_flush
        & (io_stall ? insts_pack_reg_0_inst_valid : io_insts_pack_RN_0_inst_valid);
      insts_pack_reg_0_predict_jump <=
        ~io_flush
        & (io_stall ? insts_pack_reg_0_predict_jump : io_insts_pack_RN_0_predict_jump);
      insts_pack_reg_0_rj_valid <=
        ~io_flush & (io_stall ? insts_pack_reg_0_rj_valid : io_insts_pack_RN_0_rj_valid);
      insts_pack_reg_0_rk_valid <=
        ~io_flush & (io_stall ? insts_pack_reg_0_rk_valid : io_insts_pack_RN_0_rk_valid);
      insts_pack_reg_0_rd_valid <=
        ~io_flush & (io_stall ? insts_pack_reg_0_rd_valid : io_insts_pack_RN_0_rd_valid);
      insts_pack_reg_1_inst_valid <=
        ~io_flush
        & (io_stall ? insts_pack_reg_1_inst_valid : io_insts_pack_RN_1_inst_valid);
      insts_pack_reg_1_predict_jump <=
        ~io_flush
        & (io_stall ? insts_pack_reg_1_predict_jump : io_insts_pack_RN_1_predict_jump);
      insts_pack_reg_1_rj_valid <=
        ~io_flush & (io_stall ? insts_pack_reg_1_rj_valid : io_insts_pack_RN_1_rj_valid);
      insts_pack_reg_1_rk_valid <=
        ~io_flush & (io_stall ? insts_pack_reg_1_rk_valid : io_insts_pack_RN_1_rk_valid);
      insts_pack_reg_1_rd_valid <=
        ~io_flush & (io_stall ? insts_pack_reg_1_rd_valid : io_insts_pack_RN_1_rd_valid);
      insts_pack_reg_1_prj_raw <=
        ~io_flush & (io_stall ? insts_pack_reg_1_prj_raw : io_insts_pack_RN_1_prj_raw);
      insts_pack_reg_1_prk_raw <=
        ~io_flush & (io_stall ? insts_pack_reg_1_prk_raw : io_insts_pack_RN_1_prk_raw);
      insts_pack_reg_2_inst_valid <=
        ~io_flush
        & (io_stall ? insts_pack_reg_2_inst_valid : io_insts_pack_RN_2_inst_valid);
      insts_pack_reg_2_predict_jump <=
        ~io_flush
        & (io_stall ? insts_pack_reg_2_predict_jump : io_insts_pack_RN_2_predict_jump);
      insts_pack_reg_2_rj_valid <=
        ~io_flush & (io_stall ? insts_pack_reg_2_rj_valid : io_insts_pack_RN_2_rj_valid);
      insts_pack_reg_2_rk_valid <=
        ~io_flush & (io_stall ? insts_pack_reg_2_rk_valid : io_insts_pack_RN_2_rk_valid);
      insts_pack_reg_2_rd_valid <=
        ~io_flush & (io_stall ? insts_pack_reg_2_rd_valid : io_insts_pack_RN_2_rd_valid);
      insts_pack_reg_2_prj_raw <=
        ~io_flush & (io_stall ? insts_pack_reg_2_prj_raw : io_insts_pack_RN_2_prj_raw);
      insts_pack_reg_2_prk_raw <=
        ~io_flush & (io_stall ? insts_pack_reg_2_prk_raw : io_insts_pack_RN_2_prk_raw);
      insts_pack_reg_3_inst_valid <=
        ~io_flush
        & (io_stall ? insts_pack_reg_3_inst_valid : io_insts_pack_RN_3_inst_valid);
      insts_pack_reg_3_predict_jump <=
        ~io_flush
        & (io_stall ? insts_pack_reg_3_predict_jump : io_insts_pack_RN_3_predict_jump);
      insts_pack_reg_3_rj_valid <=
        ~io_flush & (io_stall ? insts_pack_reg_3_rj_valid : io_insts_pack_RN_3_rj_valid);
      insts_pack_reg_3_rk_valid <=
        ~io_flush & (io_stall ? insts_pack_reg_3_rk_valid : io_insts_pack_RN_3_rk_valid);
      insts_pack_reg_3_rd_valid <=
        ~io_flush & (io_stall ? insts_pack_reg_3_rd_valid : io_insts_pack_RN_3_rd_valid);
      insts_pack_reg_3_prj_raw <=
        ~io_flush & (io_stall ? insts_pack_reg_3_prj_raw : io_insts_pack_RN_3_prj_raw);
      insts_pack_reg_3_prk_raw <=
        ~io_flush & (io_stall ? insts_pack_reg_3_prk_raw : io_insts_pack_RN_3_prk_raw);
    end
  end // always @(posedge)
  assign io_insts_pack_DP_0_pc = insts_pack_reg_0_pc;
  assign io_insts_pack_DP_0_inst_valid = insts_pack_reg_0_inst_valid;
  assign io_insts_pack_DP_0_predict_jump = insts_pack_reg_0_predict_jump;
  assign io_insts_pack_DP_0_pred_npc = insts_pack_reg_0_pred_npc;
  assign io_insts_pack_DP_0_rj_valid = insts_pack_reg_0_rj_valid;
  assign io_insts_pack_DP_0_rk_valid = insts_pack_reg_0_rk_valid;
  assign io_insts_pack_DP_0_rd_valid = insts_pack_reg_0_rd_valid;
  assign io_insts_pack_DP_0_imm = insts_pack_reg_0_imm;
  assign io_insts_pack_DP_0_alu_op = insts_pack_reg_0_alu_op;
  assign io_insts_pack_DP_0_alu_rs1_sel = insts_pack_reg_0_alu_rs1_sel;
  assign io_insts_pack_DP_0_alu_rs2_sel = insts_pack_reg_0_alu_rs2_sel;
  assign io_insts_pack_DP_0_br_type = insts_pack_reg_0_br_type;
  assign io_insts_pack_DP_0_mem_type = insts_pack_reg_0_mem_type;
  assign io_insts_pack_DP_0_fu_id = insts_pack_reg_0_fu_id;
  assign io_insts_pack_DP_0_prj = insts_pack_reg_0_prj;
  assign io_insts_pack_DP_0_prk = insts_pack_reg_0_prk;
  assign io_insts_pack_DP_0_prd = insts_pack_reg_0_prd;
  assign io_insts_pack_DP_0_rob_index = insts_pack_reg_0_rob_index;
  assign io_insts_pack_DP_1_pc = insts_pack_reg_1_pc;
  assign io_insts_pack_DP_1_inst_valid = insts_pack_reg_1_inst_valid;
  assign io_insts_pack_DP_1_predict_jump = insts_pack_reg_1_predict_jump;
  assign io_insts_pack_DP_1_pred_npc = insts_pack_reg_1_pred_npc;
  assign io_insts_pack_DP_1_rj_valid = insts_pack_reg_1_rj_valid;
  assign io_insts_pack_DP_1_rk_valid = insts_pack_reg_1_rk_valid;
  assign io_insts_pack_DP_1_rd_valid = insts_pack_reg_1_rd_valid;
  assign io_insts_pack_DP_1_imm = insts_pack_reg_1_imm;
  assign io_insts_pack_DP_1_alu_op = insts_pack_reg_1_alu_op;
  assign io_insts_pack_DP_1_alu_rs1_sel = insts_pack_reg_1_alu_rs1_sel;
  assign io_insts_pack_DP_1_alu_rs2_sel = insts_pack_reg_1_alu_rs2_sel;
  assign io_insts_pack_DP_1_br_type = insts_pack_reg_1_br_type;
  assign io_insts_pack_DP_1_mem_type = insts_pack_reg_1_mem_type;
  assign io_insts_pack_DP_1_fu_id = insts_pack_reg_1_fu_id;
  assign io_insts_pack_DP_1_prj = insts_pack_reg_1_prj;
  assign io_insts_pack_DP_1_prk = insts_pack_reg_1_prk;
  assign io_insts_pack_DP_1_prd = insts_pack_reg_1_prd;
  assign io_insts_pack_DP_1_rob_index = insts_pack_reg_1_rob_index;
  assign io_insts_pack_DP_1_prj_raw = insts_pack_reg_1_prj_raw;
  assign io_insts_pack_DP_1_prk_raw = insts_pack_reg_1_prk_raw;
  assign io_insts_pack_DP_2_pc = insts_pack_reg_2_pc;
  assign io_insts_pack_DP_2_inst_valid = insts_pack_reg_2_inst_valid;
  assign io_insts_pack_DP_2_predict_jump = insts_pack_reg_2_predict_jump;
  assign io_insts_pack_DP_2_pred_npc = insts_pack_reg_2_pred_npc;
  assign io_insts_pack_DP_2_rj_valid = insts_pack_reg_2_rj_valid;
  assign io_insts_pack_DP_2_rk_valid = insts_pack_reg_2_rk_valid;
  assign io_insts_pack_DP_2_rd_valid = insts_pack_reg_2_rd_valid;
  assign io_insts_pack_DP_2_imm = insts_pack_reg_2_imm;
  assign io_insts_pack_DP_2_alu_op = insts_pack_reg_2_alu_op;
  assign io_insts_pack_DP_2_alu_rs1_sel = insts_pack_reg_2_alu_rs1_sel;
  assign io_insts_pack_DP_2_alu_rs2_sel = insts_pack_reg_2_alu_rs2_sel;
  assign io_insts_pack_DP_2_br_type = insts_pack_reg_2_br_type;
  assign io_insts_pack_DP_2_mem_type = insts_pack_reg_2_mem_type;
  assign io_insts_pack_DP_2_fu_id = insts_pack_reg_2_fu_id;
  assign io_insts_pack_DP_2_prj = insts_pack_reg_2_prj;
  assign io_insts_pack_DP_2_prk = insts_pack_reg_2_prk;
  assign io_insts_pack_DP_2_prd = insts_pack_reg_2_prd;
  assign io_insts_pack_DP_2_rob_index = insts_pack_reg_2_rob_index;
  assign io_insts_pack_DP_2_prj_raw = insts_pack_reg_2_prj_raw;
  assign io_insts_pack_DP_2_prk_raw = insts_pack_reg_2_prk_raw;
  assign io_insts_pack_DP_3_pc = insts_pack_reg_3_pc;
  assign io_insts_pack_DP_3_inst_valid = insts_pack_reg_3_inst_valid;
  assign io_insts_pack_DP_3_predict_jump = insts_pack_reg_3_predict_jump;
  assign io_insts_pack_DP_3_pred_npc = insts_pack_reg_3_pred_npc;
  assign io_insts_pack_DP_3_rj_valid = insts_pack_reg_3_rj_valid;
  assign io_insts_pack_DP_3_rk_valid = insts_pack_reg_3_rk_valid;
  assign io_insts_pack_DP_3_rd_valid = insts_pack_reg_3_rd_valid;
  assign io_insts_pack_DP_3_imm = insts_pack_reg_3_imm;
  assign io_insts_pack_DP_3_alu_op = insts_pack_reg_3_alu_op;
  assign io_insts_pack_DP_3_alu_rs1_sel = insts_pack_reg_3_alu_rs1_sel;
  assign io_insts_pack_DP_3_alu_rs2_sel = insts_pack_reg_3_alu_rs2_sel;
  assign io_insts_pack_DP_3_br_type = insts_pack_reg_3_br_type;
  assign io_insts_pack_DP_3_mem_type = insts_pack_reg_3_mem_type;
  assign io_insts_pack_DP_3_fu_id = insts_pack_reg_3_fu_id;
  assign io_insts_pack_DP_3_prj = insts_pack_reg_3_prj;
  assign io_insts_pack_DP_3_prk = insts_pack_reg_3_prk;
  assign io_insts_pack_DP_3_prd = insts_pack_reg_3_prd;
  assign io_insts_pack_DP_3_rob_index = insts_pack_reg_3_rob_index;
  assign io_insts_pack_DP_3_prj_raw = insts_pack_reg_3_prj_raw;
  assign io_insts_pack_DP_3_prk_raw = insts_pack_reg_3_prk_raw;
endmodule

