// Generated by CIRCT firtool-1.58.0
module Unorder_Issue_Queue_2(
  input         clock,
                reset,
  input  [1:0]  io_insts_disp_index_0,
                io_insts_disp_index_1,
                io_insts_disp_index_2,
                io_insts_disp_index_3,
  input         io_insts_disp_valid_0,
                io_insts_disp_valid_1,
                io_insts_disp_valid_2,
                io_insts_disp_valid_3,
  input  [6:0]  io_insts_dispatch_0_prj,
                io_insts_dispatch_0_prk,
  input         io_insts_dispatch_0_rd_valid,
  input  [6:0]  io_insts_dispatch_0_prd,
  input  [31:0] io_insts_dispatch_0_imm,
  input  [5:0]  io_insts_dispatch_0_rob_index,
  input  [4:0]  io_insts_dispatch_0_mem_type,
  input  [6:0]  io_insts_dispatch_1_prj,
                io_insts_dispatch_1_prk,
  input         io_insts_dispatch_1_rd_valid,
  input  [6:0]  io_insts_dispatch_1_prd,
  input  [31:0] io_insts_dispatch_1_imm,
  input  [5:0]  io_insts_dispatch_1_rob_index,
  input  [4:0]  io_insts_dispatch_1_mem_type,
  input  [6:0]  io_insts_dispatch_2_prj,
                io_insts_dispatch_2_prk,
  input         io_insts_dispatch_2_rd_valid,
  input  [6:0]  io_insts_dispatch_2_prd,
  input  [31:0] io_insts_dispatch_2_imm,
  input  [5:0]  io_insts_dispatch_2_rob_index,
  input  [4:0]  io_insts_dispatch_2_mem_type,
  input  [6:0]  io_insts_dispatch_3_prj,
                io_insts_dispatch_3_prk,
  input         io_insts_dispatch_3_rd_valid,
  input  [6:0]  io_insts_dispatch_3_prd,
  input  [31:0] io_insts_dispatch_3_imm,
  input  [5:0]  io_insts_dispatch_3_rob_index,
  input  [4:0]  io_insts_dispatch_3_mem_type,
  input         io_prj_ready_0,
                io_prj_ready_1,
                io_prj_ready_2,
                io_prj_ready_3,
                io_prk_ready_0,
                io_prk_ready_1,
                io_prk_ready_2,
                io_prk_ready_3,
  input  [6:0]  io_wake_preg_0,
                io_wake_preg_1,
                io_wake_preg_2,
                io_wake_preg_3,
  input         io_issue_ack_0,
                io_issue_ack_1,
                io_issue_ack_2,
                io_issue_ack_3,
                io_issue_ack_4,
                io_issue_ack_5,
                io_issue_ack_6,
                io_issue_ack_7,
  output [6:0]  io_insts_issue_0_inst_prj,
                io_insts_issue_0_inst_prk,
  output        io_insts_issue_0_inst_rd_valid,
  output [6:0]  io_insts_issue_0_inst_prd,
  output [31:0] io_insts_issue_0_inst_imm,
  output [5:0]  io_insts_issue_0_inst_rob_index,
  output [4:0]  io_insts_issue_0_inst_mem_type,
  output [6:0]  io_insts_issue_1_inst_prj,
                io_insts_issue_1_inst_prk,
  output        io_insts_issue_1_inst_rd_valid,
  output [6:0]  io_insts_issue_1_inst_prd,
  output [31:0] io_insts_issue_1_inst_imm,
  output [5:0]  io_insts_issue_1_inst_rob_index,
  output [4:0]  io_insts_issue_1_inst_mem_type,
  output [6:0]  io_insts_issue_2_inst_prj,
                io_insts_issue_2_inst_prk,
  output        io_insts_issue_2_inst_rd_valid,
  output [6:0]  io_insts_issue_2_inst_prd,
  output [31:0] io_insts_issue_2_inst_imm,
  output [5:0]  io_insts_issue_2_inst_rob_index,
  output [4:0]  io_insts_issue_2_inst_mem_type,
  output [6:0]  io_insts_issue_3_inst_prj,
                io_insts_issue_3_inst_prk,
  output        io_insts_issue_3_inst_rd_valid,
  output [6:0]  io_insts_issue_3_inst_prd,
  output [31:0] io_insts_issue_3_inst_imm,
  output [5:0]  io_insts_issue_3_inst_rob_index,
  output [4:0]  io_insts_issue_3_inst_mem_type,
  output [6:0]  io_insts_issue_4_inst_prj,
                io_insts_issue_4_inst_prk,
  output        io_insts_issue_4_inst_rd_valid,
  output [6:0]  io_insts_issue_4_inst_prd,
  output [31:0] io_insts_issue_4_inst_imm,
  output [5:0]  io_insts_issue_4_inst_rob_index,
  output [4:0]  io_insts_issue_4_inst_mem_type,
  output [6:0]  io_insts_issue_5_inst_prj,
                io_insts_issue_5_inst_prk,
  output        io_insts_issue_5_inst_rd_valid,
  output [6:0]  io_insts_issue_5_inst_prd,
  output [31:0] io_insts_issue_5_inst_imm,
  output [5:0]  io_insts_issue_5_inst_rob_index,
  output [4:0]  io_insts_issue_5_inst_mem_type,
  output [6:0]  io_insts_issue_6_inst_prj,
                io_insts_issue_6_inst_prk,
  output        io_insts_issue_6_inst_rd_valid,
  output [6:0]  io_insts_issue_6_inst_prd,
  output [31:0] io_insts_issue_6_inst_imm,
  output [5:0]  io_insts_issue_6_inst_rob_index,
  output [4:0]  io_insts_issue_6_inst_mem_type,
  output [6:0]  io_insts_issue_7_inst_prj,
                io_insts_issue_7_inst_prk,
  output        io_insts_issue_7_inst_rd_valid,
  output [6:0]  io_insts_issue_7_inst_prd,
  output [31:0] io_insts_issue_7_inst_imm,
  output [5:0]  io_insts_issue_7_inst_rob_index,
  output [4:0]  io_insts_issue_7_inst_mem_type,
  output        io_issue_req_0,
                io_issue_req_1,
                io_issue_req_2,
                io_issue_req_3,
                io_issue_req_4,
                io_issue_req_5,
                io_issue_req_6,
                io_issue_req_7,
                io_full,
  input         io_stall,
                io_flush
);

  wire [3:0]  _tail_pop_T_16;
  reg         casez_tmp;
  reg  [1:0]  casez_tmp_0;
  reg  [6:0]  casez_tmp_1;
  reg  [6:0]  casez_tmp_2;
  reg         casez_tmp_3;
  reg  [6:0]  casez_tmp_4;
  reg  [31:0] casez_tmp_5;
  reg  [5:0]  casez_tmp_6;
  reg  [4:0]  casez_tmp_7;
  reg         casez_tmp_8;
  reg         casez_tmp_9;
  reg         casez_tmp_10;
  reg  [1:0]  casez_tmp_11;
  reg  [6:0]  casez_tmp_12;
  reg  [6:0]  casez_tmp_13;
  reg         casez_tmp_14;
  reg  [6:0]  casez_tmp_15;
  reg  [31:0] casez_tmp_16;
  reg  [5:0]  casez_tmp_17;
  reg  [4:0]  casez_tmp_18;
  reg         casez_tmp_19;
  reg         casez_tmp_20;
  reg         casez_tmp_21;
  reg  [1:0]  casez_tmp_22;
  reg  [6:0]  casez_tmp_23;
  reg  [6:0]  casez_tmp_24;
  reg         casez_tmp_25;
  reg  [6:0]  casez_tmp_26;
  reg  [31:0] casez_tmp_27;
  reg  [5:0]  casez_tmp_28;
  reg  [4:0]  casez_tmp_29;
  reg         casez_tmp_30;
  reg         casez_tmp_31;
  reg         casez_tmp_32;
  reg  [1:0]  casez_tmp_33;
  reg  [6:0]  casez_tmp_34;
  reg  [6:0]  casez_tmp_35;
  reg         casez_tmp_36;
  reg  [6:0]  casez_tmp_37;
  reg  [31:0] casez_tmp_38;
  reg  [5:0]  casez_tmp_39;
  reg  [4:0]  casez_tmp_40;
  reg         casez_tmp_41;
  reg         casez_tmp_42;
  reg         casez_tmp_43;
  reg  [1:0]  casez_tmp_44;
  reg  [6:0]  casez_tmp_45;
  reg  [6:0]  casez_tmp_46;
  reg         casez_tmp_47;
  reg  [6:0]  casez_tmp_48;
  reg  [31:0] casez_tmp_49;
  reg  [5:0]  casez_tmp_50;
  reg  [4:0]  casez_tmp_51;
  reg         casez_tmp_52;
  reg         casez_tmp_53;
  reg         casez_tmp_54;
  reg  [1:0]  casez_tmp_55;
  reg  [6:0]  casez_tmp_56;
  reg  [6:0]  casez_tmp_57;
  reg         casez_tmp_58;
  reg  [6:0]  casez_tmp_59;
  reg  [31:0] casez_tmp_60;
  reg  [5:0]  casez_tmp_61;
  reg  [4:0]  casez_tmp_62;
  reg         casez_tmp_63;
  reg         casez_tmp_64;
  reg         casez_tmp_65;
  reg  [1:0]  casez_tmp_66;
  reg  [6:0]  casez_tmp_67;
  reg  [6:0]  casez_tmp_68;
  reg         casez_tmp_69;
  reg  [6:0]  casez_tmp_70;
  reg  [31:0] casez_tmp_71;
  reg  [5:0]  casez_tmp_72;
  reg  [4:0]  casez_tmp_73;
  reg         casez_tmp_74;
  reg         casez_tmp_75;
  reg         casez_tmp_76;
  reg  [1:0]  casez_tmp_77;
  reg  [6:0]  casez_tmp_78;
  reg  [6:0]  casez_tmp_79;
  reg         casez_tmp_80;
  reg  [6:0]  casez_tmp_81;
  reg  [31:0] casez_tmp_82;
  reg  [5:0]  casez_tmp_83;
  reg  [4:0]  casez_tmp_84;
  reg         casez_tmp_85;
  reg         casez_tmp_86;
  reg  [6:0]  queue_0_inst_prj;
  reg  [6:0]  queue_0_inst_prk;
  reg         queue_0_inst_rd_valid;
  reg  [6:0]  queue_0_inst_prd;
  reg  [31:0] queue_0_inst_imm;
  reg  [5:0]  queue_0_inst_rob_index;
  reg  [4:0]  queue_0_inst_mem_type;
  reg         queue_0_prj_waked;
  reg         queue_0_prk_waked;
  reg  [6:0]  queue_1_inst_prj;
  reg  [6:0]  queue_1_inst_prk;
  reg         queue_1_inst_rd_valid;
  reg  [6:0]  queue_1_inst_prd;
  reg  [31:0] queue_1_inst_imm;
  reg  [5:0]  queue_1_inst_rob_index;
  reg  [4:0]  queue_1_inst_mem_type;
  reg         queue_1_prj_waked;
  reg         queue_1_prk_waked;
  reg  [6:0]  queue_2_inst_prj;
  reg  [6:0]  queue_2_inst_prk;
  reg         queue_2_inst_rd_valid;
  reg  [6:0]  queue_2_inst_prd;
  reg  [31:0] queue_2_inst_imm;
  reg  [5:0]  queue_2_inst_rob_index;
  reg  [4:0]  queue_2_inst_mem_type;
  reg         queue_2_prj_waked;
  reg         queue_2_prk_waked;
  reg  [6:0]  queue_3_inst_prj;
  reg  [6:0]  queue_3_inst_prk;
  reg         queue_3_inst_rd_valid;
  reg  [6:0]  queue_3_inst_prd;
  reg  [31:0] queue_3_inst_imm;
  reg  [5:0]  queue_3_inst_rob_index;
  reg  [4:0]  queue_3_inst_mem_type;
  reg         queue_3_prj_waked;
  reg         queue_3_prk_waked;
  reg  [6:0]  queue_4_inst_prj;
  reg  [6:0]  queue_4_inst_prk;
  reg         queue_4_inst_rd_valid;
  reg  [6:0]  queue_4_inst_prd;
  reg  [31:0] queue_4_inst_imm;
  reg  [5:0]  queue_4_inst_rob_index;
  reg  [4:0]  queue_4_inst_mem_type;
  reg         queue_4_prj_waked;
  reg         queue_4_prk_waked;
  reg  [6:0]  queue_5_inst_prj;
  reg  [6:0]  queue_5_inst_prk;
  reg         queue_5_inst_rd_valid;
  reg  [6:0]  queue_5_inst_prd;
  reg  [31:0] queue_5_inst_imm;
  reg  [5:0]  queue_5_inst_rob_index;
  reg  [4:0]  queue_5_inst_mem_type;
  reg         queue_5_prj_waked;
  reg         queue_5_prk_waked;
  reg  [6:0]  queue_6_inst_prj;
  reg  [6:0]  queue_6_inst_prk;
  reg         queue_6_inst_rd_valid;
  reg  [6:0]  queue_6_inst_prd;
  reg  [31:0] queue_6_inst_imm;
  reg  [5:0]  queue_6_inst_rob_index;
  reg  [4:0]  queue_6_inst_mem_type;
  reg         queue_6_prj_waked;
  reg         queue_6_prk_waked;
  reg  [6:0]  queue_7_inst_prj;
  reg  [6:0]  queue_7_inst_prk;
  reg         queue_7_inst_rd_valid;
  reg  [6:0]  queue_7_inst_prd;
  reg  [31:0] queue_7_inst_imm;
  reg  [5:0]  queue_7_inst_rob_index;
  reg  [4:0]  queue_7_inst_mem_type;
  reg         queue_7_prj_waked;
  reg         queue_7_prk_waked;
  reg  [3:0]  tail;
  wire [2:0]  insert_num =
    {1'h0, {1'h0, io_insts_disp_valid_0} + {1'h0, io_insts_disp_valid_1}}
    + {1'h0, {1'h0, io_insts_disp_valid_2} + {1'h0, io_insts_disp_valid_3}};
  wire        full = _tail_pop_T_16 >= 4'h8 - {1'h0, insert_num};
  assign _tail_pop_T_16 =
    tail
    - {3'h0,
       io_issue_ack_0 | io_issue_ack_1 | io_issue_ack_2 | io_issue_ack_3 | io_issue_ack_4
         | io_issue_ack_5 | io_issue_ack_6 | io_issue_ack_7};
  wire [1:0]  _queue_next_0_inst_T_4 = 2'h0 - _tail_pop_T_16[1:0];
  always_comb begin
    casez (_queue_next_0_inst_T_4)
      2'b00:
        casez_tmp = io_insts_disp_valid_0;
      2'b01:
        casez_tmp = io_insts_disp_valid_1;
      2'b10:
        casez_tmp = io_insts_disp_valid_2;
      default:
        casez_tmp = io_insts_disp_valid_3;
    endcase
  end // always_comb
  always_comb begin
    casez (_queue_next_0_inst_T_4)
      2'b00:
        casez_tmp_0 = io_insts_disp_index_0;
      2'b01:
        casez_tmp_0 = io_insts_disp_index_1;
      2'b10:
        casez_tmp_0 = io_insts_disp_index_2;
      default:
        casez_tmp_0 = io_insts_disp_index_3;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_0)
      2'b00:
        casez_tmp_1 = io_insts_dispatch_0_prj;
      2'b01:
        casez_tmp_1 = io_insts_dispatch_1_prj;
      2'b10:
        casez_tmp_1 = io_insts_dispatch_2_prj;
      default:
        casez_tmp_1 = io_insts_dispatch_3_prj;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_0)
      2'b00:
        casez_tmp_2 = io_insts_dispatch_0_prk;
      2'b01:
        casez_tmp_2 = io_insts_dispatch_1_prk;
      2'b10:
        casez_tmp_2 = io_insts_dispatch_2_prk;
      default:
        casez_tmp_2 = io_insts_dispatch_3_prk;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_0)
      2'b00:
        casez_tmp_3 = io_insts_dispatch_0_rd_valid;
      2'b01:
        casez_tmp_3 = io_insts_dispatch_1_rd_valid;
      2'b10:
        casez_tmp_3 = io_insts_dispatch_2_rd_valid;
      default:
        casez_tmp_3 = io_insts_dispatch_3_rd_valid;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_0)
      2'b00:
        casez_tmp_4 = io_insts_dispatch_0_prd;
      2'b01:
        casez_tmp_4 = io_insts_dispatch_1_prd;
      2'b10:
        casez_tmp_4 = io_insts_dispatch_2_prd;
      default:
        casez_tmp_4 = io_insts_dispatch_3_prd;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_0)
      2'b00:
        casez_tmp_5 = io_insts_dispatch_0_imm;
      2'b01:
        casez_tmp_5 = io_insts_dispatch_1_imm;
      2'b10:
        casez_tmp_5 = io_insts_dispatch_2_imm;
      default:
        casez_tmp_5 = io_insts_dispatch_3_imm;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_0)
      2'b00:
        casez_tmp_6 = io_insts_dispatch_0_rob_index;
      2'b01:
        casez_tmp_6 = io_insts_dispatch_1_rob_index;
      2'b10:
        casez_tmp_6 = io_insts_dispatch_2_rob_index;
      default:
        casez_tmp_6 = io_insts_dispatch_3_rob_index;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_0)
      2'b00:
        casez_tmp_7 = io_insts_dispatch_0_mem_type;
      2'b01:
        casez_tmp_7 = io_insts_dispatch_1_mem_type;
      2'b10:
        casez_tmp_7 = io_insts_dispatch_2_mem_type;
      default:
        casez_tmp_7 = io_insts_dispatch_3_mem_type;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_0)
      2'b00:
        casez_tmp_8 = io_prj_ready_0;
      2'b01:
        casez_tmp_8 = io_prj_ready_1;
      2'b10:
        casez_tmp_8 = io_prj_ready_2;
      default:
        casez_tmp_8 = io_prj_ready_3;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_0)
      2'b00:
        casez_tmp_9 = io_prk_ready_0;
      2'b01:
        casez_tmp_9 = io_prk_ready_1;
      2'b10:
        casez_tmp_9 = io_prk_ready_2;
      default:
        casez_tmp_9 = io_prk_ready_3;
    endcase
  end // always_comb
  wire [1:0]  _queue_next_1_prk_waked_T_5 = 2'h1 - _tail_pop_T_16[1:0];
  always_comb begin
    casez (_queue_next_1_prk_waked_T_5)
      2'b00:
        casez_tmp_10 = io_insts_disp_valid_0;
      2'b01:
        casez_tmp_10 = io_insts_disp_valid_1;
      2'b10:
        casez_tmp_10 = io_insts_disp_valid_2;
      default:
        casez_tmp_10 = io_insts_disp_valid_3;
    endcase
  end // always_comb
  always_comb begin
    casez (_queue_next_1_prk_waked_T_5)
      2'b00:
        casez_tmp_11 = io_insts_disp_index_0;
      2'b01:
        casez_tmp_11 = io_insts_disp_index_1;
      2'b10:
        casez_tmp_11 = io_insts_disp_index_2;
      default:
        casez_tmp_11 = io_insts_disp_index_3;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_11)
      2'b00:
        casez_tmp_12 = io_insts_dispatch_0_prj;
      2'b01:
        casez_tmp_12 = io_insts_dispatch_1_prj;
      2'b10:
        casez_tmp_12 = io_insts_dispatch_2_prj;
      default:
        casez_tmp_12 = io_insts_dispatch_3_prj;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_11)
      2'b00:
        casez_tmp_13 = io_insts_dispatch_0_prk;
      2'b01:
        casez_tmp_13 = io_insts_dispatch_1_prk;
      2'b10:
        casez_tmp_13 = io_insts_dispatch_2_prk;
      default:
        casez_tmp_13 = io_insts_dispatch_3_prk;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_11)
      2'b00:
        casez_tmp_14 = io_insts_dispatch_0_rd_valid;
      2'b01:
        casez_tmp_14 = io_insts_dispatch_1_rd_valid;
      2'b10:
        casez_tmp_14 = io_insts_dispatch_2_rd_valid;
      default:
        casez_tmp_14 = io_insts_dispatch_3_rd_valid;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_11)
      2'b00:
        casez_tmp_15 = io_insts_dispatch_0_prd;
      2'b01:
        casez_tmp_15 = io_insts_dispatch_1_prd;
      2'b10:
        casez_tmp_15 = io_insts_dispatch_2_prd;
      default:
        casez_tmp_15 = io_insts_dispatch_3_prd;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_11)
      2'b00:
        casez_tmp_16 = io_insts_dispatch_0_imm;
      2'b01:
        casez_tmp_16 = io_insts_dispatch_1_imm;
      2'b10:
        casez_tmp_16 = io_insts_dispatch_2_imm;
      default:
        casez_tmp_16 = io_insts_dispatch_3_imm;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_11)
      2'b00:
        casez_tmp_17 = io_insts_dispatch_0_rob_index;
      2'b01:
        casez_tmp_17 = io_insts_dispatch_1_rob_index;
      2'b10:
        casez_tmp_17 = io_insts_dispatch_2_rob_index;
      default:
        casez_tmp_17 = io_insts_dispatch_3_rob_index;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_11)
      2'b00:
        casez_tmp_18 = io_insts_dispatch_0_mem_type;
      2'b01:
        casez_tmp_18 = io_insts_dispatch_1_mem_type;
      2'b10:
        casez_tmp_18 = io_insts_dispatch_2_mem_type;
      default:
        casez_tmp_18 = io_insts_dispatch_3_mem_type;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_11)
      2'b00:
        casez_tmp_19 = io_prj_ready_0;
      2'b01:
        casez_tmp_19 = io_prj_ready_1;
      2'b10:
        casez_tmp_19 = io_prj_ready_2;
      default:
        casez_tmp_19 = io_prj_ready_3;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_11)
      2'b00:
        casez_tmp_20 = io_prk_ready_0;
      2'b01:
        casez_tmp_20 = io_prk_ready_1;
      2'b10:
        casez_tmp_20 = io_prk_ready_2;
      default:
        casez_tmp_20 = io_prk_ready_3;
    endcase
  end // always_comb
  wire [1:0]  _queue_next_2_prk_waked_T_5 = 2'h2 - _tail_pop_T_16[1:0];
  always_comb begin
    casez (_queue_next_2_prk_waked_T_5)
      2'b00:
        casez_tmp_21 = io_insts_disp_valid_0;
      2'b01:
        casez_tmp_21 = io_insts_disp_valid_1;
      2'b10:
        casez_tmp_21 = io_insts_disp_valid_2;
      default:
        casez_tmp_21 = io_insts_disp_valid_3;
    endcase
  end // always_comb
  always_comb begin
    casez (_queue_next_2_prk_waked_T_5)
      2'b00:
        casez_tmp_22 = io_insts_disp_index_0;
      2'b01:
        casez_tmp_22 = io_insts_disp_index_1;
      2'b10:
        casez_tmp_22 = io_insts_disp_index_2;
      default:
        casez_tmp_22 = io_insts_disp_index_3;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_22)
      2'b00:
        casez_tmp_23 = io_insts_dispatch_0_prj;
      2'b01:
        casez_tmp_23 = io_insts_dispatch_1_prj;
      2'b10:
        casez_tmp_23 = io_insts_dispatch_2_prj;
      default:
        casez_tmp_23 = io_insts_dispatch_3_prj;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_22)
      2'b00:
        casez_tmp_24 = io_insts_dispatch_0_prk;
      2'b01:
        casez_tmp_24 = io_insts_dispatch_1_prk;
      2'b10:
        casez_tmp_24 = io_insts_dispatch_2_prk;
      default:
        casez_tmp_24 = io_insts_dispatch_3_prk;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_22)
      2'b00:
        casez_tmp_25 = io_insts_dispatch_0_rd_valid;
      2'b01:
        casez_tmp_25 = io_insts_dispatch_1_rd_valid;
      2'b10:
        casez_tmp_25 = io_insts_dispatch_2_rd_valid;
      default:
        casez_tmp_25 = io_insts_dispatch_3_rd_valid;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_22)
      2'b00:
        casez_tmp_26 = io_insts_dispatch_0_prd;
      2'b01:
        casez_tmp_26 = io_insts_dispatch_1_prd;
      2'b10:
        casez_tmp_26 = io_insts_dispatch_2_prd;
      default:
        casez_tmp_26 = io_insts_dispatch_3_prd;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_22)
      2'b00:
        casez_tmp_27 = io_insts_dispatch_0_imm;
      2'b01:
        casez_tmp_27 = io_insts_dispatch_1_imm;
      2'b10:
        casez_tmp_27 = io_insts_dispatch_2_imm;
      default:
        casez_tmp_27 = io_insts_dispatch_3_imm;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_22)
      2'b00:
        casez_tmp_28 = io_insts_dispatch_0_rob_index;
      2'b01:
        casez_tmp_28 = io_insts_dispatch_1_rob_index;
      2'b10:
        casez_tmp_28 = io_insts_dispatch_2_rob_index;
      default:
        casez_tmp_28 = io_insts_dispatch_3_rob_index;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_22)
      2'b00:
        casez_tmp_29 = io_insts_dispatch_0_mem_type;
      2'b01:
        casez_tmp_29 = io_insts_dispatch_1_mem_type;
      2'b10:
        casez_tmp_29 = io_insts_dispatch_2_mem_type;
      default:
        casez_tmp_29 = io_insts_dispatch_3_mem_type;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_22)
      2'b00:
        casez_tmp_30 = io_prj_ready_0;
      2'b01:
        casez_tmp_30 = io_prj_ready_1;
      2'b10:
        casez_tmp_30 = io_prj_ready_2;
      default:
        casez_tmp_30 = io_prj_ready_3;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_22)
      2'b00:
        casez_tmp_31 = io_prk_ready_0;
      2'b01:
        casez_tmp_31 = io_prk_ready_1;
      2'b10:
        casez_tmp_31 = io_prk_ready_2;
      default:
        casez_tmp_31 = io_prk_ready_3;
    endcase
  end // always_comb
  wire [1:0]  _queue_next_3_prk_waked_T_5 = 2'h3 - _tail_pop_T_16[1:0];
  always_comb begin
    casez (_queue_next_3_prk_waked_T_5)
      2'b00:
        casez_tmp_32 = io_insts_disp_valid_0;
      2'b01:
        casez_tmp_32 = io_insts_disp_valid_1;
      2'b10:
        casez_tmp_32 = io_insts_disp_valid_2;
      default:
        casez_tmp_32 = io_insts_disp_valid_3;
    endcase
  end // always_comb
  always_comb begin
    casez (_queue_next_3_prk_waked_T_5)
      2'b00:
        casez_tmp_33 = io_insts_disp_index_0;
      2'b01:
        casez_tmp_33 = io_insts_disp_index_1;
      2'b10:
        casez_tmp_33 = io_insts_disp_index_2;
      default:
        casez_tmp_33 = io_insts_disp_index_3;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_33)
      2'b00:
        casez_tmp_34 = io_insts_dispatch_0_prj;
      2'b01:
        casez_tmp_34 = io_insts_dispatch_1_prj;
      2'b10:
        casez_tmp_34 = io_insts_dispatch_2_prj;
      default:
        casez_tmp_34 = io_insts_dispatch_3_prj;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_33)
      2'b00:
        casez_tmp_35 = io_insts_dispatch_0_prk;
      2'b01:
        casez_tmp_35 = io_insts_dispatch_1_prk;
      2'b10:
        casez_tmp_35 = io_insts_dispatch_2_prk;
      default:
        casez_tmp_35 = io_insts_dispatch_3_prk;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_33)
      2'b00:
        casez_tmp_36 = io_insts_dispatch_0_rd_valid;
      2'b01:
        casez_tmp_36 = io_insts_dispatch_1_rd_valid;
      2'b10:
        casez_tmp_36 = io_insts_dispatch_2_rd_valid;
      default:
        casez_tmp_36 = io_insts_dispatch_3_rd_valid;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_33)
      2'b00:
        casez_tmp_37 = io_insts_dispatch_0_prd;
      2'b01:
        casez_tmp_37 = io_insts_dispatch_1_prd;
      2'b10:
        casez_tmp_37 = io_insts_dispatch_2_prd;
      default:
        casez_tmp_37 = io_insts_dispatch_3_prd;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_33)
      2'b00:
        casez_tmp_38 = io_insts_dispatch_0_imm;
      2'b01:
        casez_tmp_38 = io_insts_dispatch_1_imm;
      2'b10:
        casez_tmp_38 = io_insts_dispatch_2_imm;
      default:
        casez_tmp_38 = io_insts_dispatch_3_imm;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_33)
      2'b00:
        casez_tmp_39 = io_insts_dispatch_0_rob_index;
      2'b01:
        casez_tmp_39 = io_insts_dispatch_1_rob_index;
      2'b10:
        casez_tmp_39 = io_insts_dispatch_2_rob_index;
      default:
        casez_tmp_39 = io_insts_dispatch_3_rob_index;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_33)
      2'b00:
        casez_tmp_40 = io_insts_dispatch_0_mem_type;
      2'b01:
        casez_tmp_40 = io_insts_dispatch_1_mem_type;
      2'b10:
        casez_tmp_40 = io_insts_dispatch_2_mem_type;
      default:
        casez_tmp_40 = io_insts_dispatch_3_mem_type;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_33)
      2'b00:
        casez_tmp_41 = io_prj_ready_0;
      2'b01:
        casez_tmp_41 = io_prj_ready_1;
      2'b10:
        casez_tmp_41 = io_prj_ready_2;
      default:
        casez_tmp_41 = io_prj_ready_3;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_33)
      2'b00:
        casez_tmp_42 = io_prk_ready_0;
      2'b01:
        casez_tmp_42 = io_prk_ready_1;
      2'b10:
        casez_tmp_42 = io_prk_ready_2;
      default:
        casez_tmp_42 = io_prk_ready_3;
    endcase
  end // always_comb
  wire [1:0]  _queue_next_4_prk_waked_T_5 = 2'h0 - _tail_pop_T_16[1:0];
  always_comb begin
    casez (_queue_next_4_prk_waked_T_5)
      2'b00:
        casez_tmp_43 = io_insts_disp_valid_0;
      2'b01:
        casez_tmp_43 = io_insts_disp_valid_1;
      2'b10:
        casez_tmp_43 = io_insts_disp_valid_2;
      default:
        casez_tmp_43 = io_insts_disp_valid_3;
    endcase
  end // always_comb
  always_comb begin
    casez (_queue_next_4_prk_waked_T_5)
      2'b00:
        casez_tmp_44 = io_insts_disp_index_0;
      2'b01:
        casez_tmp_44 = io_insts_disp_index_1;
      2'b10:
        casez_tmp_44 = io_insts_disp_index_2;
      default:
        casez_tmp_44 = io_insts_disp_index_3;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_44)
      2'b00:
        casez_tmp_45 = io_insts_dispatch_0_prj;
      2'b01:
        casez_tmp_45 = io_insts_dispatch_1_prj;
      2'b10:
        casez_tmp_45 = io_insts_dispatch_2_prj;
      default:
        casez_tmp_45 = io_insts_dispatch_3_prj;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_44)
      2'b00:
        casez_tmp_46 = io_insts_dispatch_0_prk;
      2'b01:
        casez_tmp_46 = io_insts_dispatch_1_prk;
      2'b10:
        casez_tmp_46 = io_insts_dispatch_2_prk;
      default:
        casez_tmp_46 = io_insts_dispatch_3_prk;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_44)
      2'b00:
        casez_tmp_47 = io_insts_dispatch_0_rd_valid;
      2'b01:
        casez_tmp_47 = io_insts_dispatch_1_rd_valid;
      2'b10:
        casez_tmp_47 = io_insts_dispatch_2_rd_valid;
      default:
        casez_tmp_47 = io_insts_dispatch_3_rd_valid;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_44)
      2'b00:
        casez_tmp_48 = io_insts_dispatch_0_prd;
      2'b01:
        casez_tmp_48 = io_insts_dispatch_1_prd;
      2'b10:
        casez_tmp_48 = io_insts_dispatch_2_prd;
      default:
        casez_tmp_48 = io_insts_dispatch_3_prd;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_44)
      2'b00:
        casez_tmp_49 = io_insts_dispatch_0_imm;
      2'b01:
        casez_tmp_49 = io_insts_dispatch_1_imm;
      2'b10:
        casez_tmp_49 = io_insts_dispatch_2_imm;
      default:
        casez_tmp_49 = io_insts_dispatch_3_imm;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_44)
      2'b00:
        casez_tmp_50 = io_insts_dispatch_0_rob_index;
      2'b01:
        casez_tmp_50 = io_insts_dispatch_1_rob_index;
      2'b10:
        casez_tmp_50 = io_insts_dispatch_2_rob_index;
      default:
        casez_tmp_50 = io_insts_dispatch_3_rob_index;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_44)
      2'b00:
        casez_tmp_51 = io_insts_dispatch_0_mem_type;
      2'b01:
        casez_tmp_51 = io_insts_dispatch_1_mem_type;
      2'b10:
        casez_tmp_51 = io_insts_dispatch_2_mem_type;
      default:
        casez_tmp_51 = io_insts_dispatch_3_mem_type;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_44)
      2'b00:
        casez_tmp_52 = io_prj_ready_0;
      2'b01:
        casez_tmp_52 = io_prj_ready_1;
      2'b10:
        casez_tmp_52 = io_prj_ready_2;
      default:
        casez_tmp_52 = io_prj_ready_3;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_44)
      2'b00:
        casez_tmp_53 = io_prk_ready_0;
      2'b01:
        casez_tmp_53 = io_prk_ready_1;
      2'b10:
        casez_tmp_53 = io_prk_ready_2;
      default:
        casez_tmp_53 = io_prk_ready_3;
    endcase
  end // always_comb
  wire [1:0]  _queue_next_5_prk_waked_T_5 = 2'h1 - _tail_pop_T_16[1:0];
  always_comb begin
    casez (_queue_next_5_prk_waked_T_5)
      2'b00:
        casez_tmp_54 = io_insts_disp_valid_0;
      2'b01:
        casez_tmp_54 = io_insts_disp_valid_1;
      2'b10:
        casez_tmp_54 = io_insts_disp_valid_2;
      default:
        casez_tmp_54 = io_insts_disp_valid_3;
    endcase
  end // always_comb
  always_comb begin
    casez (_queue_next_5_prk_waked_T_5)
      2'b00:
        casez_tmp_55 = io_insts_disp_index_0;
      2'b01:
        casez_tmp_55 = io_insts_disp_index_1;
      2'b10:
        casez_tmp_55 = io_insts_disp_index_2;
      default:
        casez_tmp_55 = io_insts_disp_index_3;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_55)
      2'b00:
        casez_tmp_56 = io_insts_dispatch_0_prj;
      2'b01:
        casez_tmp_56 = io_insts_dispatch_1_prj;
      2'b10:
        casez_tmp_56 = io_insts_dispatch_2_prj;
      default:
        casez_tmp_56 = io_insts_dispatch_3_prj;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_55)
      2'b00:
        casez_tmp_57 = io_insts_dispatch_0_prk;
      2'b01:
        casez_tmp_57 = io_insts_dispatch_1_prk;
      2'b10:
        casez_tmp_57 = io_insts_dispatch_2_prk;
      default:
        casez_tmp_57 = io_insts_dispatch_3_prk;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_55)
      2'b00:
        casez_tmp_58 = io_insts_dispatch_0_rd_valid;
      2'b01:
        casez_tmp_58 = io_insts_dispatch_1_rd_valid;
      2'b10:
        casez_tmp_58 = io_insts_dispatch_2_rd_valid;
      default:
        casez_tmp_58 = io_insts_dispatch_3_rd_valid;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_55)
      2'b00:
        casez_tmp_59 = io_insts_dispatch_0_prd;
      2'b01:
        casez_tmp_59 = io_insts_dispatch_1_prd;
      2'b10:
        casez_tmp_59 = io_insts_dispatch_2_prd;
      default:
        casez_tmp_59 = io_insts_dispatch_3_prd;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_55)
      2'b00:
        casez_tmp_60 = io_insts_dispatch_0_imm;
      2'b01:
        casez_tmp_60 = io_insts_dispatch_1_imm;
      2'b10:
        casez_tmp_60 = io_insts_dispatch_2_imm;
      default:
        casez_tmp_60 = io_insts_dispatch_3_imm;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_55)
      2'b00:
        casez_tmp_61 = io_insts_dispatch_0_rob_index;
      2'b01:
        casez_tmp_61 = io_insts_dispatch_1_rob_index;
      2'b10:
        casez_tmp_61 = io_insts_dispatch_2_rob_index;
      default:
        casez_tmp_61 = io_insts_dispatch_3_rob_index;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_55)
      2'b00:
        casez_tmp_62 = io_insts_dispatch_0_mem_type;
      2'b01:
        casez_tmp_62 = io_insts_dispatch_1_mem_type;
      2'b10:
        casez_tmp_62 = io_insts_dispatch_2_mem_type;
      default:
        casez_tmp_62 = io_insts_dispatch_3_mem_type;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_55)
      2'b00:
        casez_tmp_63 = io_prj_ready_0;
      2'b01:
        casez_tmp_63 = io_prj_ready_1;
      2'b10:
        casez_tmp_63 = io_prj_ready_2;
      default:
        casez_tmp_63 = io_prj_ready_3;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_55)
      2'b00:
        casez_tmp_64 = io_prk_ready_0;
      2'b01:
        casez_tmp_64 = io_prk_ready_1;
      2'b10:
        casez_tmp_64 = io_prk_ready_2;
      default:
        casez_tmp_64 = io_prk_ready_3;
    endcase
  end // always_comb
  wire [1:0]  _queue_next_6_prk_waked_T_5 = 2'h2 - _tail_pop_T_16[1:0];
  always_comb begin
    casez (_queue_next_6_prk_waked_T_5)
      2'b00:
        casez_tmp_65 = io_insts_disp_valid_0;
      2'b01:
        casez_tmp_65 = io_insts_disp_valid_1;
      2'b10:
        casez_tmp_65 = io_insts_disp_valid_2;
      default:
        casez_tmp_65 = io_insts_disp_valid_3;
    endcase
  end // always_comb
  always_comb begin
    casez (_queue_next_6_prk_waked_T_5)
      2'b00:
        casez_tmp_66 = io_insts_disp_index_0;
      2'b01:
        casez_tmp_66 = io_insts_disp_index_1;
      2'b10:
        casez_tmp_66 = io_insts_disp_index_2;
      default:
        casez_tmp_66 = io_insts_disp_index_3;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_66)
      2'b00:
        casez_tmp_67 = io_insts_dispatch_0_prj;
      2'b01:
        casez_tmp_67 = io_insts_dispatch_1_prj;
      2'b10:
        casez_tmp_67 = io_insts_dispatch_2_prj;
      default:
        casez_tmp_67 = io_insts_dispatch_3_prj;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_66)
      2'b00:
        casez_tmp_68 = io_insts_dispatch_0_prk;
      2'b01:
        casez_tmp_68 = io_insts_dispatch_1_prk;
      2'b10:
        casez_tmp_68 = io_insts_dispatch_2_prk;
      default:
        casez_tmp_68 = io_insts_dispatch_3_prk;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_66)
      2'b00:
        casez_tmp_69 = io_insts_dispatch_0_rd_valid;
      2'b01:
        casez_tmp_69 = io_insts_dispatch_1_rd_valid;
      2'b10:
        casez_tmp_69 = io_insts_dispatch_2_rd_valid;
      default:
        casez_tmp_69 = io_insts_dispatch_3_rd_valid;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_66)
      2'b00:
        casez_tmp_70 = io_insts_dispatch_0_prd;
      2'b01:
        casez_tmp_70 = io_insts_dispatch_1_prd;
      2'b10:
        casez_tmp_70 = io_insts_dispatch_2_prd;
      default:
        casez_tmp_70 = io_insts_dispatch_3_prd;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_66)
      2'b00:
        casez_tmp_71 = io_insts_dispatch_0_imm;
      2'b01:
        casez_tmp_71 = io_insts_dispatch_1_imm;
      2'b10:
        casez_tmp_71 = io_insts_dispatch_2_imm;
      default:
        casez_tmp_71 = io_insts_dispatch_3_imm;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_66)
      2'b00:
        casez_tmp_72 = io_insts_dispatch_0_rob_index;
      2'b01:
        casez_tmp_72 = io_insts_dispatch_1_rob_index;
      2'b10:
        casez_tmp_72 = io_insts_dispatch_2_rob_index;
      default:
        casez_tmp_72 = io_insts_dispatch_3_rob_index;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_66)
      2'b00:
        casez_tmp_73 = io_insts_dispatch_0_mem_type;
      2'b01:
        casez_tmp_73 = io_insts_dispatch_1_mem_type;
      2'b10:
        casez_tmp_73 = io_insts_dispatch_2_mem_type;
      default:
        casez_tmp_73 = io_insts_dispatch_3_mem_type;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_66)
      2'b00:
        casez_tmp_74 = io_prj_ready_0;
      2'b01:
        casez_tmp_74 = io_prj_ready_1;
      2'b10:
        casez_tmp_74 = io_prj_ready_2;
      default:
        casez_tmp_74 = io_prj_ready_3;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_66)
      2'b00:
        casez_tmp_75 = io_prk_ready_0;
      2'b01:
        casez_tmp_75 = io_prk_ready_1;
      2'b10:
        casez_tmp_75 = io_prk_ready_2;
      default:
        casez_tmp_75 = io_prk_ready_3;
    endcase
  end // always_comb
  wire [1:0]  _queue_next_7_prk_waked_T_5 = 2'h3 - _tail_pop_T_16[1:0];
  always_comb begin
    casez (_queue_next_7_prk_waked_T_5)
      2'b00:
        casez_tmp_76 = io_insts_disp_valid_0;
      2'b01:
        casez_tmp_76 = io_insts_disp_valid_1;
      2'b10:
        casez_tmp_76 = io_insts_disp_valid_2;
      default:
        casez_tmp_76 = io_insts_disp_valid_3;
    endcase
  end // always_comb
  always_comb begin
    casez (_queue_next_7_prk_waked_T_5)
      2'b00:
        casez_tmp_77 = io_insts_disp_index_0;
      2'b01:
        casez_tmp_77 = io_insts_disp_index_1;
      2'b10:
        casez_tmp_77 = io_insts_disp_index_2;
      default:
        casez_tmp_77 = io_insts_disp_index_3;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_77)
      2'b00:
        casez_tmp_78 = io_insts_dispatch_0_prj;
      2'b01:
        casez_tmp_78 = io_insts_dispatch_1_prj;
      2'b10:
        casez_tmp_78 = io_insts_dispatch_2_prj;
      default:
        casez_tmp_78 = io_insts_dispatch_3_prj;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_77)
      2'b00:
        casez_tmp_79 = io_insts_dispatch_0_prk;
      2'b01:
        casez_tmp_79 = io_insts_dispatch_1_prk;
      2'b10:
        casez_tmp_79 = io_insts_dispatch_2_prk;
      default:
        casez_tmp_79 = io_insts_dispatch_3_prk;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_77)
      2'b00:
        casez_tmp_80 = io_insts_dispatch_0_rd_valid;
      2'b01:
        casez_tmp_80 = io_insts_dispatch_1_rd_valid;
      2'b10:
        casez_tmp_80 = io_insts_dispatch_2_rd_valid;
      default:
        casez_tmp_80 = io_insts_dispatch_3_rd_valid;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_77)
      2'b00:
        casez_tmp_81 = io_insts_dispatch_0_prd;
      2'b01:
        casez_tmp_81 = io_insts_dispatch_1_prd;
      2'b10:
        casez_tmp_81 = io_insts_dispatch_2_prd;
      default:
        casez_tmp_81 = io_insts_dispatch_3_prd;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_77)
      2'b00:
        casez_tmp_82 = io_insts_dispatch_0_imm;
      2'b01:
        casez_tmp_82 = io_insts_dispatch_1_imm;
      2'b10:
        casez_tmp_82 = io_insts_dispatch_2_imm;
      default:
        casez_tmp_82 = io_insts_dispatch_3_imm;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_77)
      2'b00:
        casez_tmp_83 = io_insts_dispatch_0_rob_index;
      2'b01:
        casez_tmp_83 = io_insts_dispatch_1_rob_index;
      2'b10:
        casez_tmp_83 = io_insts_dispatch_2_rob_index;
      default:
        casez_tmp_83 = io_insts_dispatch_3_rob_index;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_77)
      2'b00:
        casez_tmp_84 = io_insts_dispatch_0_mem_type;
      2'b01:
        casez_tmp_84 = io_insts_dispatch_1_mem_type;
      2'b10:
        casez_tmp_84 = io_insts_dispatch_2_mem_type;
      default:
        casez_tmp_84 = io_insts_dispatch_3_mem_type;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_77)
      2'b00:
        casez_tmp_85 = io_prj_ready_0;
      2'b01:
        casez_tmp_85 = io_prj_ready_1;
      2'b10:
        casez_tmp_85 = io_prj_ready_2;
      default:
        casez_tmp_85 = io_prj_ready_3;
    endcase
  end // always_comb
  always_comb begin
    casez (casez_tmp_77)
      2'b00:
        casez_tmp_86 = io_prk_ready_0;
      2'b01:
        casez_tmp_86 = io_prk_ready_1;
      2'b10:
        casez_tmp_86 = io_prk_ready_2;
      default:
        casez_tmp_86 = io_prk_ready_3;
    endcase
  end // always_comb
  wire [7:0]  next_mask =
    ~({io_issue_ack_7,
       io_issue_ack_6,
       io_issue_ack_5,
       io_issue_ack_4,
       io_issue_ack_3,
       io_issue_ack_2,
       io_issue_ack_1,
       io_issue_ack_0} - 8'h1);
  wire [6:0]  _queue_next_0_inst_T_8_prj = casez_tmp ? casez_tmp_1 : 7'h0;
  wire [6:0]  _queue_next_0_inst_T_8_prk = casez_tmp ? casez_tmp_2 : 7'h0;
  wire [6:0]  queue_next_0_inst_prj =
    (|_tail_pop_T_16)
      ? (next_mask[0] ? queue_1_inst_prj : queue_0_inst_prj)
      : _queue_next_0_inst_T_8_prj;
  wire [6:0]  queue_next_0_inst_prk =
    (|_tail_pop_T_16)
      ? (next_mask[0] ? queue_1_inst_prk : queue_0_inst_prk)
      : _queue_next_0_inst_T_8_prk;
  wire [6:0]  _queue_next_1_inst_T_8_prj = casez_tmp_10 ? casez_tmp_12 : 7'h0;
  wire [6:0]  _queue_next_1_inst_T_8_prk = casez_tmp_10 ? casez_tmp_13 : 7'h0;
  wire [6:0]  queue_next_1_inst_prj =
    (|(_tail_pop_T_16[3:1]))
      ? (next_mask[1] ? queue_2_inst_prj : queue_1_inst_prj)
      : _queue_next_1_inst_T_8_prj;
  wire [6:0]  queue_next_1_inst_prk =
    (|(_tail_pop_T_16[3:1]))
      ? (next_mask[1] ? queue_2_inst_prk : queue_1_inst_prk)
      : _queue_next_1_inst_T_8_prk;
  wire        _GEN = _tail_pop_T_16 > 4'h2;
  wire [6:0]  _queue_next_2_inst_T_8_prj = casez_tmp_21 ? casez_tmp_23 : 7'h0;
  wire [6:0]  _queue_next_2_inst_T_8_prk = casez_tmp_21 ? casez_tmp_24 : 7'h0;
  wire [6:0]  queue_next_2_inst_prj =
    _GEN
      ? (next_mask[2] ? queue_3_inst_prj : queue_2_inst_prj)
      : _queue_next_2_inst_T_8_prj;
  wire [6:0]  queue_next_2_inst_prk =
    _GEN
      ? (next_mask[2] ? queue_3_inst_prk : queue_2_inst_prk)
      : _queue_next_2_inst_T_8_prk;
  wire [6:0]  _queue_next_3_inst_T_8_prj = casez_tmp_32 ? casez_tmp_34 : 7'h0;
  wire [6:0]  _queue_next_3_inst_T_8_prk = casez_tmp_32 ? casez_tmp_35 : 7'h0;
  wire [6:0]  queue_next_3_inst_prj =
    (|(_tail_pop_T_16[3:2]))
      ? (next_mask[3] ? queue_4_inst_prj : queue_3_inst_prj)
      : _queue_next_3_inst_T_8_prj;
  wire [6:0]  queue_next_3_inst_prk =
    (|(_tail_pop_T_16[3:2]))
      ? (next_mask[3] ? queue_4_inst_prk : queue_3_inst_prk)
      : _queue_next_3_inst_T_8_prk;
  wire        _GEN_0 = _tail_pop_T_16 > 4'h4;
  wire [6:0]  _queue_next_4_inst_T_8_prj = casez_tmp_43 ? casez_tmp_45 : 7'h0;
  wire [6:0]  _queue_next_4_inst_T_8_prk = casez_tmp_43 ? casez_tmp_46 : 7'h0;
  wire [6:0]  queue_next_4_inst_prj =
    _GEN_0
      ? (next_mask[4] ? queue_5_inst_prj : queue_4_inst_prj)
      : _queue_next_4_inst_T_8_prj;
  wire [6:0]  queue_next_4_inst_prk =
    _GEN_0
      ? (next_mask[4] ? queue_5_inst_prk : queue_4_inst_prk)
      : _queue_next_4_inst_T_8_prk;
  wire        _GEN_1 = _tail_pop_T_16 > 4'h5;
  wire [6:0]  _queue_next_5_inst_T_8_prj = casez_tmp_54 ? casez_tmp_56 : 7'h0;
  wire [6:0]  _queue_next_5_inst_T_8_prk = casez_tmp_54 ? casez_tmp_57 : 7'h0;
  wire [6:0]  queue_next_5_inst_prj =
    _GEN_1
      ? (next_mask[5] ? queue_6_inst_prj : queue_5_inst_prj)
      : _queue_next_5_inst_T_8_prj;
  wire [6:0]  queue_next_5_inst_prk =
    _GEN_1
      ? (next_mask[5] ? queue_6_inst_prk : queue_5_inst_prk)
      : _queue_next_5_inst_T_8_prk;
  wire        _GEN_2 = _tail_pop_T_16 > 4'h6;
  wire [6:0]  _queue_next_6_inst_T_8_prj = casez_tmp_65 ? casez_tmp_67 : 7'h0;
  wire [6:0]  _queue_next_6_inst_T_8_prk = casez_tmp_65 ? casez_tmp_68 : 7'h0;
  wire [6:0]  queue_next_6_inst_prj =
    _GEN_2
      ? (next_mask[6] ? queue_7_inst_prj : queue_6_inst_prj)
      : _queue_next_6_inst_T_8_prj;
  wire [6:0]  queue_next_6_inst_prk =
    _GEN_2
      ? (next_mask[6] ? queue_7_inst_prk : queue_6_inst_prk)
      : _queue_next_6_inst_T_8_prk;
  wire [6:0]  _queue_next_7_inst_T_8_prj = casez_tmp_76 ? casez_tmp_78 : 7'h0;
  wire [6:0]  _queue_next_7_inst_T_8_prk = casez_tmp_76 ? casez_tmp_79 : 7'h0;
  wire [6:0]  queue_next_7_inst_prj =
    _tail_pop_T_16[3]
      ? (next_mask[7] ? 7'h0 : queue_7_inst_prj)
      : _queue_next_7_inst_T_8_prj;
  wire [6:0]  queue_next_7_inst_prk =
    _tail_pop_T_16[3]
      ? (next_mask[7] ? 7'h0 : queue_7_inst_prk)
      : _queue_next_7_inst_T_8_prk;
  always @(posedge clock) begin
    if (reset) begin
      queue_0_inst_prj <= 7'h0;
      queue_0_inst_prk <= 7'h0;
      queue_0_inst_rd_valid <= 1'h0;
      queue_0_inst_prd <= 7'h0;
      queue_0_inst_imm <= 32'h0;
      queue_0_inst_rob_index <= 6'h0;
      queue_0_inst_mem_type <= 5'h0;
      queue_0_prj_waked <= 1'h0;
      queue_0_prk_waked <= 1'h0;
      queue_1_inst_prj <= 7'h0;
      queue_1_inst_prk <= 7'h0;
      queue_1_inst_rd_valid <= 1'h0;
      queue_1_inst_prd <= 7'h0;
      queue_1_inst_imm <= 32'h0;
      queue_1_inst_rob_index <= 6'h0;
      queue_1_inst_mem_type <= 5'h0;
      queue_1_prj_waked <= 1'h0;
      queue_1_prk_waked <= 1'h0;
      queue_2_inst_prj <= 7'h0;
      queue_2_inst_prk <= 7'h0;
      queue_2_inst_rd_valid <= 1'h0;
      queue_2_inst_prd <= 7'h0;
      queue_2_inst_imm <= 32'h0;
      queue_2_inst_rob_index <= 6'h0;
      queue_2_inst_mem_type <= 5'h0;
      queue_2_prj_waked <= 1'h0;
      queue_2_prk_waked <= 1'h0;
      queue_3_inst_prj <= 7'h0;
      queue_3_inst_prk <= 7'h0;
      queue_3_inst_rd_valid <= 1'h0;
      queue_3_inst_prd <= 7'h0;
      queue_3_inst_imm <= 32'h0;
      queue_3_inst_rob_index <= 6'h0;
      queue_3_inst_mem_type <= 5'h0;
      queue_3_prj_waked <= 1'h0;
      queue_3_prk_waked <= 1'h0;
      queue_4_inst_prj <= 7'h0;
      queue_4_inst_prk <= 7'h0;
      queue_4_inst_rd_valid <= 1'h0;
      queue_4_inst_prd <= 7'h0;
      queue_4_inst_imm <= 32'h0;
      queue_4_inst_rob_index <= 6'h0;
      queue_4_inst_mem_type <= 5'h0;
      queue_4_prj_waked <= 1'h0;
      queue_4_prk_waked <= 1'h0;
      queue_5_inst_prj <= 7'h0;
      queue_5_inst_prk <= 7'h0;
      queue_5_inst_rd_valid <= 1'h0;
      queue_5_inst_prd <= 7'h0;
      queue_5_inst_imm <= 32'h0;
      queue_5_inst_rob_index <= 6'h0;
      queue_5_inst_mem_type <= 5'h0;
      queue_5_prj_waked <= 1'h0;
      queue_5_prk_waked <= 1'h0;
      queue_6_inst_prj <= 7'h0;
      queue_6_inst_prk <= 7'h0;
      queue_6_inst_rd_valid <= 1'h0;
      queue_6_inst_prd <= 7'h0;
      queue_6_inst_imm <= 32'h0;
      queue_6_inst_rob_index <= 6'h0;
      queue_6_inst_mem_type <= 5'h0;
      queue_6_prj_waked <= 1'h0;
      queue_6_prk_waked <= 1'h0;
      queue_7_inst_prj <= 7'h0;
      queue_7_inst_prk <= 7'h0;
      queue_7_inst_rd_valid <= 1'h0;
      queue_7_inst_prd <= 7'h0;
      queue_7_inst_imm <= 32'h0;
      queue_7_inst_rob_index <= 6'h0;
      queue_7_inst_mem_type <= 5'h0;
      queue_7_prj_waked <= 1'h0;
      queue_7_prk_waked <= 1'h0;
      tail <= 4'h0;
    end
    else begin
      if (|_tail_pop_T_16) begin
        if (next_mask[0]) begin
          queue_0_inst_prj <= queue_1_inst_prj;
          queue_0_inst_prk <= queue_1_inst_prk;
          queue_0_inst_rd_valid <= queue_1_inst_rd_valid;
          queue_0_inst_prd <= queue_1_inst_prd;
          queue_0_inst_imm <= queue_1_inst_imm;
          queue_0_inst_rob_index <= queue_1_inst_rob_index;
          queue_0_inst_mem_type <= queue_1_inst_mem_type;
        end
      end
      else begin
        queue_0_inst_prj <= _queue_next_0_inst_T_8_prj;
        queue_0_inst_prk <= _queue_next_0_inst_T_8_prk;
        queue_0_inst_rd_valid <= casez_tmp & casez_tmp_3;
        queue_0_inst_prd <= casez_tmp ? casez_tmp_4 : 7'h0;
        queue_0_inst_imm <= casez_tmp ? casez_tmp_5 : 32'h0;
        queue_0_inst_rob_index <= casez_tmp ? casez_tmp_6 : 6'h0;
        queue_0_inst_mem_type <= casez_tmp ? casez_tmp_7 : 5'h0;
      end
      queue_0_prj_waked <=
        ((|_tail_pop_T_16)
           ? (next_mask[0] ? queue_1_prj_waked : queue_0_prj_waked)
           : casez_tmp & casez_tmp_8)
        | (|{queue_next_0_inst_prj == io_wake_preg_3,
             queue_next_0_inst_prj == io_wake_preg_2,
             queue_next_0_inst_prj == io_wake_preg_1,
             queue_next_0_inst_prj == io_wake_preg_0});
      queue_0_prk_waked <=
        ((|_tail_pop_T_16)
           ? (next_mask[0] ? queue_1_prk_waked : queue_0_prk_waked)
           : casez_tmp & casez_tmp_9)
        | (|{queue_next_0_inst_prk == io_wake_preg_3,
             queue_next_0_inst_prk == io_wake_preg_2,
             queue_next_0_inst_prk == io_wake_preg_1,
             queue_next_0_inst_prk == io_wake_preg_0});
      if (|(_tail_pop_T_16[3:1])) begin
        if (next_mask[1]) begin
          queue_1_inst_prj <= queue_2_inst_prj;
          queue_1_inst_prk <= queue_2_inst_prk;
          queue_1_inst_rd_valid <= queue_2_inst_rd_valid;
          queue_1_inst_prd <= queue_2_inst_prd;
          queue_1_inst_imm <= queue_2_inst_imm;
          queue_1_inst_rob_index <= queue_2_inst_rob_index;
          queue_1_inst_mem_type <= queue_2_inst_mem_type;
        end
      end
      else begin
        queue_1_inst_prj <= _queue_next_1_inst_T_8_prj;
        queue_1_inst_prk <= _queue_next_1_inst_T_8_prk;
        queue_1_inst_rd_valid <= casez_tmp_10 & casez_tmp_14;
        queue_1_inst_prd <= casez_tmp_10 ? casez_tmp_15 : 7'h0;
        queue_1_inst_imm <= casez_tmp_10 ? casez_tmp_16 : 32'h0;
        queue_1_inst_rob_index <= casez_tmp_10 ? casez_tmp_17 : 6'h0;
        queue_1_inst_mem_type <= casez_tmp_10 ? casez_tmp_18 : 5'h0;
      end
      queue_1_prj_waked <=
        ((|(_tail_pop_T_16[3:1]))
           ? (next_mask[1] ? queue_2_prj_waked : queue_1_prj_waked)
           : casez_tmp_10 & casez_tmp_19)
        | (|{queue_next_1_inst_prj == io_wake_preg_3,
             queue_next_1_inst_prj == io_wake_preg_2,
             queue_next_1_inst_prj == io_wake_preg_1,
             queue_next_1_inst_prj == io_wake_preg_0});
      queue_1_prk_waked <=
        ((|(_tail_pop_T_16[3:1]))
           ? (next_mask[1] ? queue_2_prk_waked : queue_1_prk_waked)
           : casez_tmp_10 & casez_tmp_20)
        | (|{queue_next_1_inst_prk == io_wake_preg_3,
             queue_next_1_inst_prk == io_wake_preg_2,
             queue_next_1_inst_prk == io_wake_preg_1,
             queue_next_1_inst_prk == io_wake_preg_0});
      if (_GEN) begin
        if (next_mask[2]) begin
          queue_2_inst_prj <= queue_3_inst_prj;
          queue_2_inst_prk <= queue_3_inst_prk;
          queue_2_inst_rd_valid <= queue_3_inst_rd_valid;
          queue_2_inst_prd <= queue_3_inst_prd;
          queue_2_inst_imm <= queue_3_inst_imm;
          queue_2_inst_rob_index <= queue_3_inst_rob_index;
          queue_2_inst_mem_type <= queue_3_inst_mem_type;
        end
      end
      else begin
        queue_2_inst_prj <= _queue_next_2_inst_T_8_prj;
        queue_2_inst_prk <= _queue_next_2_inst_T_8_prk;
        queue_2_inst_rd_valid <= casez_tmp_21 & casez_tmp_25;
        queue_2_inst_prd <= casez_tmp_21 ? casez_tmp_26 : 7'h0;
        queue_2_inst_imm <= casez_tmp_21 ? casez_tmp_27 : 32'h0;
        queue_2_inst_rob_index <= casez_tmp_21 ? casez_tmp_28 : 6'h0;
        queue_2_inst_mem_type <= casez_tmp_21 ? casez_tmp_29 : 5'h0;
      end
      queue_2_prj_waked <=
        (_GEN
           ? (next_mask[2] ? queue_3_prj_waked : queue_2_prj_waked)
           : casez_tmp_21 & casez_tmp_30)
        | (|{queue_next_2_inst_prj == io_wake_preg_3,
             queue_next_2_inst_prj == io_wake_preg_2,
             queue_next_2_inst_prj == io_wake_preg_1,
             queue_next_2_inst_prj == io_wake_preg_0});
      queue_2_prk_waked <=
        (_GEN
           ? (next_mask[2] ? queue_3_prk_waked : queue_2_prk_waked)
           : casez_tmp_21 & casez_tmp_31)
        | (|{queue_next_2_inst_prk == io_wake_preg_3,
             queue_next_2_inst_prk == io_wake_preg_2,
             queue_next_2_inst_prk == io_wake_preg_1,
             queue_next_2_inst_prk == io_wake_preg_0});
      if (|(_tail_pop_T_16[3:2])) begin
        if (next_mask[3]) begin
          queue_3_inst_prj <= queue_4_inst_prj;
          queue_3_inst_prk <= queue_4_inst_prk;
          queue_3_inst_rd_valid <= queue_4_inst_rd_valid;
          queue_3_inst_prd <= queue_4_inst_prd;
          queue_3_inst_imm <= queue_4_inst_imm;
          queue_3_inst_rob_index <= queue_4_inst_rob_index;
          queue_3_inst_mem_type <= queue_4_inst_mem_type;
        end
      end
      else begin
        queue_3_inst_prj <= _queue_next_3_inst_T_8_prj;
        queue_3_inst_prk <= _queue_next_3_inst_T_8_prk;
        queue_3_inst_rd_valid <= casez_tmp_32 & casez_tmp_36;
        queue_3_inst_prd <= casez_tmp_32 ? casez_tmp_37 : 7'h0;
        queue_3_inst_imm <= casez_tmp_32 ? casez_tmp_38 : 32'h0;
        queue_3_inst_rob_index <= casez_tmp_32 ? casez_tmp_39 : 6'h0;
        queue_3_inst_mem_type <= casez_tmp_32 ? casez_tmp_40 : 5'h0;
      end
      queue_3_prj_waked <=
        ((|(_tail_pop_T_16[3:2]))
           ? (next_mask[3] ? queue_4_prj_waked : queue_3_prj_waked)
           : casez_tmp_32 & casez_tmp_41)
        | (|{queue_next_3_inst_prj == io_wake_preg_3,
             queue_next_3_inst_prj == io_wake_preg_2,
             queue_next_3_inst_prj == io_wake_preg_1,
             queue_next_3_inst_prj == io_wake_preg_0});
      queue_3_prk_waked <=
        ((|(_tail_pop_T_16[3:2]))
           ? (next_mask[3] ? queue_4_prk_waked : queue_3_prk_waked)
           : casez_tmp_32 & casez_tmp_42)
        | (|{queue_next_3_inst_prk == io_wake_preg_3,
             queue_next_3_inst_prk == io_wake_preg_2,
             queue_next_3_inst_prk == io_wake_preg_1,
             queue_next_3_inst_prk == io_wake_preg_0});
      if (_GEN_0) begin
        if (next_mask[4]) begin
          queue_4_inst_prj <= queue_5_inst_prj;
          queue_4_inst_prk <= queue_5_inst_prk;
          queue_4_inst_rd_valid <= queue_5_inst_rd_valid;
          queue_4_inst_prd <= queue_5_inst_prd;
          queue_4_inst_imm <= queue_5_inst_imm;
          queue_4_inst_rob_index <= queue_5_inst_rob_index;
          queue_4_inst_mem_type <= queue_5_inst_mem_type;
        end
      end
      else begin
        queue_4_inst_prj <= _queue_next_4_inst_T_8_prj;
        queue_4_inst_prk <= _queue_next_4_inst_T_8_prk;
        queue_4_inst_rd_valid <= casez_tmp_43 & casez_tmp_47;
        queue_4_inst_prd <= casez_tmp_43 ? casez_tmp_48 : 7'h0;
        queue_4_inst_imm <= casez_tmp_43 ? casez_tmp_49 : 32'h0;
        queue_4_inst_rob_index <= casez_tmp_43 ? casez_tmp_50 : 6'h0;
        queue_4_inst_mem_type <= casez_tmp_43 ? casez_tmp_51 : 5'h0;
      end
      queue_4_prj_waked <=
        (_GEN_0
           ? (next_mask[4] ? queue_5_prj_waked : queue_4_prj_waked)
           : casez_tmp_43 & casez_tmp_52)
        | (|{queue_next_4_inst_prj == io_wake_preg_3,
             queue_next_4_inst_prj == io_wake_preg_2,
             queue_next_4_inst_prj == io_wake_preg_1,
             queue_next_4_inst_prj == io_wake_preg_0});
      queue_4_prk_waked <=
        (_GEN_0
           ? (next_mask[4] ? queue_5_prk_waked : queue_4_prk_waked)
           : casez_tmp_43 & casez_tmp_53)
        | (|{queue_next_4_inst_prk == io_wake_preg_3,
             queue_next_4_inst_prk == io_wake_preg_2,
             queue_next_4_inst_prk == io_wake_preg_1,
             queue_next_4_inst_prk == io_wake_preg_0});
      if (_GEN_1) begin
        if (next_mask[5]) begin
          queue_5_inst_prj <= queue_6_inst_prj;
          queue_5_inst_prk <= queue_6_inst_prk;
          queue_5_inst_rd_valid <= queue_6_inst_rd_valid;
          queue_5_inst_prd <= queue_6_inst_prd;
          queue_5_inst_imm <= queue_6_inst_imm;
          queue_5_inst_rob_index <= queue_6_inst_rob_index;
          queue_5_inst_mem_type <= queue_6_inst_mem_type;
        end
      end
      else begin
        queue_5_inst_prj <= _queue_next_5_inst_T_8_prj;
        queue_5_inst_prk <= _queue_next_5_inst_T_8_prk;
        queue_5_inst_rd_valid <= casez_tmp_54 & casez_tmp_58;
        queue_5_inst_prd <= casez_tmp_54 ? casez_tmp_59 : 7'h0;
        queue_5_inst_imm <= casez_tmp_54 ? casez_tmp_60 : 32'h0;
        queue_5_inst_rob_index <= casez_tmp_54 ? casez_tmp_61 : 6'h0;
        queue_5_inst_mem_type <= casez_tmp_54 ? casez_tmp_62 : 5'h0;
      end
      queue_5_prj_waked <=
        (_GEN_1
           ? (next_mask[5] ? queue_6_prj_waked : queue_5_prj_waked)
           : casez_tmp_54 & casez_tmp_63)
        | (|{queue_next_5_inst_prj == io_wake_preg_3,
             queue_next_5_inst_prj == io_wake_preg_2,
             queue_next_5_inst_prj == io_wake_preg_1,
             queue_next_5_inst_prj == io_wake_preg_0});
      queue_5_prk_waked <=
        (_GEN_1
           ? (next_mask[5] ? queue_6_prk_waked : queue_5_prk_waked)
           : casez_tmp_54 & casez_tmp_64)
        | (|{queue_next_5_inst_prk == io_wake_preg_3,
             queue_next_5_inst_prk == io_wake_preg_2,
             queue_next_5_inst_prk == io_wake_preg_1,
             queue_next_5_inst_prk == io_wake_preg_0});
      if (_GEN_2) begin
        if (next_mask[6]) begin
          queue_6_inst_prj <= queue_7_inst_prj;
          queue_6_inst_prk <= queue_7_inst_prk;
          queue_6_inst_rd_valid <= queue_7_inst_rd_valid;
          queue_6_inst_prd <= queue_7_inst_prd;
          queue_6_inst_imm <= queue_7_inst_imm;
          queue_6_inst_rob_index <= queue_7_inst_rob_index;
          queue_6_inst_mem_type <= queue_7_inst_mem_type;
        end
      end
      else begin
        queue_6_inst_prj <= _queue_next_6_inst_T_8_prj;
        queue_6_inst_prk <= _queue_next_6_inst_T_8_prk;
        queue_6_inst_rd_valid <= casez_tmp_65 & casez_tmp_69;
        queue_6_inst_prd <= casez_tmp_65 ? casez_tmp_70 : 7'h0;
        queue_6_inst_imm <= casez_tmp_65 ? casez_tmp_71 : 32'h0;
        queue_6_inst_rob_index <= casez_tmp_65 ? casez_tmp_72 : 6'h0;
        queue_6_inst_mem_type <= casez_tmp_65 ? casez_tmp_73 : 5'h0;
      end
      queue_6_prj_waked <=
        (_GEN_2
           ? (next_mask[6] ? queue_7_prj_waked : queue_6_prj_waked)
           : casez_tmp_65 & casez_tmp_74)
        | (|{queue_next_6_inst_prj == io_wake_preg_3,
             queue_next_6_inst_prj == io_wake_preg_2,
             queue_next_6_inst_prj == io_wake_preg_1,
             queue_next_6_inst_prj == io_wake_preg_0});
      queue_6_prk_waked <=
        (_GEN_2
           ? (next_mask[6] ? queue_7_prk_waked : queue_6_prk_waked)
           : casez_tmp_65 & casez_tmp_75)
        | (|{queue_next_6_inst_prk == io_wake_preg_3,
             queue_next_6_inst_prk == io_wake_preg_2,
             queue_next_6_inst_prk == io_wake_preg_1,
             queue_next_6_inst_prk == io_wake_preg_0});
      if (_tail_pop_T_16[3]) begin
        if (next_mask[7]) begin
          queue_7_inst_prj <= 7'h0;
          queue_7_inst_prk <= 7'h0;
          queue_7_inst_prd <= 7'h0;
          queue_7_inst_imm <= 32'h0;
          queue_7_inst_rob_index <= 6'h0;
          queue_7_inst_mem_type <= 5'h0;
        end
        queue_7_inst_rd_valid <= ~(next_mask[7]) & queue_7_inst_rd_valid;
      end
      else begin
        queue_7_inst_prj <= _queue_next_7_inst_T_8_prj;
        queue_7_inst_prk <= _queue_next_7_inst_T_8_prk;
        queue_7_inst_rd_valid <= casez_tmp_76 & casez_tmp_80;
        queue_7_inst_prd <= casez_tmp_76 ? casez_tmp_81 : 7'h0;
        queue_7_inst_imm <= casez_tmp_76 ? casez_tmp_82 : 32'h0;
        queue_7_inst_rob_index <= casez_tmp_76 ? casez_tmp_83 : 6'h0;
        queue_7_inst_mem_type <= casez_tmp_76 ? casez_tmp_84 : 5'h0;
      end
      queue_7_prj_waked <=
        (_tail_pop_T_16[3]
           ? ~(next_mask[7]) & queue_7_prj_waked
           : casez_tmp_76 & casez_tmp_85)
        | (|{queue_next_7_inst_prj == io_wake_preg_3,
             queue_next_7_inst_prj == io_wake_preg_2,
             queue_next_7_inst_prj == io_wake_preg_1,
             queue_next_7_inst_prj == io_wake_preg_0});
      queue_7_prk_waked <=
        (_tail_pop_T_16[3]
           ? ~(next_mask[7]) & queue_7_prk_waked
           : casez_tmp_76 & casez_tmp_86)
        | (|{queue_next_7_inst_prk == io_wake_preg_3,
             queue_next_7_inst_prk == io_wake_preg_2,
             queue_next_7_inst_prk == io_wake_preg_1,
             queue_next_7_inst_prk == io_wake_preg_0});
      if (io_flush)
        tail <= 4'h0;
      else if (io_stall)
        tail <= _tail_pop_T_16;
      else
        tail <= _tail_pop_T_16 + {1'h0, full ? 3'h0 : insert_num};
    end
  end // always @(posedge)
  assign io_insts_issue_0_inst_prj = queue_0_inst_prj;
  assign io_insts_issue_0_inst_prk = queue_0_inst_prk;
  assign io_insts_issue_0_inst_rd_valid = queue_0_inst_rd_valid;
  assign io_insts_issue_0_inst_prd = queue_0_inst_prd;
  assign io_insts_issue_0_inst_imm = queue_0_inst_imm;
  assign io_insts_issue_0_inst_rob_index = queue_0_inst_rob_index;
  assign io_insts_issue_0_inst_mem_type = queue_0_inst_mem_type;
  assign io_insts_issue_1_inst_prj = queue_1_inst_prj;
  assign io_insts_issue_1_inst_prk = queue_1_inst_prk;
  assign io_insts_issue_1_inst_rd_valid = queue_1_inst_rd_valid;
  assign io_insts_issue_1_inst_prd = queue_1_inst_prd;
  assign io_insts_issue_1_inst_imm = queue_1_inst_imm;
  assign io_insts_issue_1_inst_rob_index = queue_1_inst_rob_index;
  assign io_insts_issue_1_inst_mem_type = queue_1_inst_mem_type;
  assign io_insts_issue_2_inst_prj = queue_2_inst_prj;
  assign io_insts_issue_2_inst_prk = queue_2_inst_prk;
  assign io_insts_issue_2_inst_rd_valid = queue_2_inst_rd_valid;
  assign io_insts_issue_2_inst_prd = queue_2_inst_prd;
  assign io_insts_issue_2_inst_imm = queue_2_inst_imm;
  assign io_insts_issue_2_inst_rob_index = queue_2_inst_rob_index;
  assign io_insts_issue_2_inst_mem_type = queue_2_inst_mem_type;
  assign io_insts_issue_3_inst_prj = queue_3_inst_prj;
  assign io_insts_issue_3_inst_prk = queue_3_inst_prk;
  assign io_insts_issue_3_inst_rd_valid = queue_3_inst_rd_valid;
  assign io_insts_issue_3_inst_prd = queue_3_inst_prd;
  assign io_insts_issue_3_inst_imm = queue_3_inst_imm;
  assign io_insts_issue_3_inst_rob_index = queue_3_inst_rob_index;
  assign io_insts_issue_3_inst_mem_type = queue_3_inst_mem_type;
  assign io_insts_issue_4_inst_prj = queue_4_inst_prj;
  assign io_insts_issue_4_inst_prk = queue_4_inst_prk;
  assign io_insts_issue_4_inst_rd_valid = queue_4_inst_rd_valid;
  assign io_insts_issue_4_inst_prd = queue_4_inst_prd;
  assign io_insts_issue_4_inst_imm = queue_4_inst_imm;
  assign io_insts_issue_4_inst_rob_index = queue_4_inst_rob_index;
  assign io_insts_issue_4_inst_mem_type = queue_4_inst_mem_type;
  assign io_insts_issue_5_inst_prj = queue_5_inst_prj;
  assign io_insts_issue_5_inst_prk = queue_5_inst_prk;
  assign io_insts_issue_5_inst_rd_valid = queue_5_inst_rd_valid;
  assign io_insts_issue_5_inst_prd = queue_5_inst_prd;
  assign io_insts_issue_5_inst_imm = queue_5_inst_imm;
  assign io_insts_issue_5_inst_rob_index = queue_5_inst_rob_index;
  assign io_insts_issue_5_inst_mem_type = queue_5_inst_mem_type;
  assign io_insts_issue_6_inst_prj = queue_6_inst_prj;
  assign io_insts_issue_6_inst_prk = queue_6_inst_prk;
  assign io_insts_issue_6_inst_rd_valid = queue_6_inst_rd_valid;
  assign io_insts_issue_6_inst_prd = queue_6_inst_prd;
  assign io_insts_issue_6_inst_imm = queue_6_inst_imm;
  assign io_insts_issue_6_inst_rob_index = queue_6_inst_rob_index;
  assign io_insts_issue_6_inst_mem_type = queue_6_inst_mem_type;
  assign io_insts_issue_7_inst_prj = queue_7_inst_prj;
  assign io_insts_issue_7_inst_prk = queue_7_inst_prk;
  assign io_insts_issue_7_inst_rd_valid = queue_7_inst_rd_valid;
  assign io_insts_issue_7_inst_prd = queue_7_inst_prd;
  assign io_insts_issue_7_inst_imm = queue_7_inst_imm;
  assign io_insts_issue_7_inst_rob_index = queue_7_inst_rob_index;
  assign io_insts_issue_7_inst_mem_type = queue_7_inst_mem_type;
  assign io_issue_req_0 = (|tail) & queue_0_prj_waked & queue_0_prk_waked;
  assign io_issue_req_1 =
    ~(queue_1_inst_mem_type[4]) & (|(tail[3:1])) & queue_1_prj_waked & queue_1_prk_waked
    & ~(queue_0_inst_mem_type[4]);
  assign io_issue_req_2 =
    ~(queue_2_inst_mem_type[4]) & tail > 4'h2 & queue_2_prj_waked & queue_2_prk_waked
    & ~(queue_0_inst_mem_type[4] | queue_1_inst_mem_type[4]);
  assign io_issue_req_3 =
    ~(queue_3_inst_mem_type[4]) & (|(tail[3:2])) & queue_3_prj_waked & queue_3_prk_waked
    & ~(queue_0_inst_mem_type[4] | queue_1_inst_mem_type[4] | queue_2_inst_mem_type[4]);
  assign io_issue_req_4 =
    ~(queue_4_inst_mem_type[4]) & tail > 4'h4 & queue_4_prj_waked & queue_4_prk_waked
    & ~(queue_0_inst_mem_type[4] | queue_1_inst_mem_type[4] | queue_2_inst_mem_type[4]
        | queue_3_inst_mem_type[4]);
  assign io_issue_req_5 =
    ~(queue_5_inst_mem_type[4]) & tail > 4'h5 & queue_5_prj_waked & queue_5_prk_waked
    & ~(queue_0_inst_mem_type[4] | queue_1_inst_mem_type[4] | queue_2_inst_mem_type[4]
        | queue_3_inst_mem_type[4] | queue_4_inst_mem_type[4]);
  assign io_issue_req_6 =
    ~(queue_6_inst_mem_type[4]) & tail > 4'h6 & queue_6_prj_waked & queue_6_prk_waked
    & ~(queue_0_inst_mem_type[4] | queue_1_inst_mem_type[4] | queue_2_inst_mem_type[4]
        | queue_3_inst_mem_type[4] | queue_4_inst_mem_type[4] | queue_5_inst_mem_type[4]);
  assign io_issue_req_7 =
    ~(queue_7_inst_mem_type[4]) & tail[3] & queue_7_prj_waked & queue_7_prk_waked
    & ~(queue_0_inst_mem_type[4] | queue_1_inst_mem_type[4] | queue_2_inst_mem_type[4]
        | queue_3_inst_mem_type[4] | queue_4_inst_mem_type[4] | queue_5_inst_mem_type[4]
        | queue_6_inst_mem_type[4]);
  assign io_full = full;
endmodule

